'use client'

import React, { createContext, useContext, useSyncExternalStore } from 'react'

export type Language = 'en' | 'id' | 'ar' | 'es'

export interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  formatNumber: (value: number | string | null | undefined) => string
  formatDate: (date?: Date | string | number, options?: Intl.DateTimeFormatOptions) => string
  isRTL: boolean
}

export function formatNumberByLang(
  value: number | string | null | undefined,
  lang: Language = 'en'
): string {
  if (value === null || value === undefined) return ''
  const str = String(value)
  if (lang === 'ar') {
    const arabicDigits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩']
    return str
      .replace(/[0-9]/g, (d) => arabicDigits[Number(d)])
      .replace(/,/g, '،')
      .replace(/%/g, '٪')
  }
  return str
}

export function formatDateByLang(
  date: Date | string | number = new Date(),
  lang: Language = 'en',
  options?: Intl.DateTimeFormatOptions
): string {
  const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date
  const localeMap: Record<Language, string> = {
    en: 'en-US',
    id: 'id-ID',
    ar: 'ar-EG',
    es: 'es-ES'
  }
  const defaultOptions: Intl.DateTimeFormatOptions = options || {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  }
  try {
    const formatted = new Intl.DateTimeFormat(localeMap[lang] || 'en-US', defaultOptions).format(d)
    return formatNumberByLang(formatted, lang)
  } catch {
    return d.toDateString()
  }
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Sidebar
    dashboard: 'Executive Dashboard',
    products: 'Product Catalog',
    production_logs: 'Production Logs',
    inventory: 'Inventory & Stock',
    reports: 'Reports & Analytics',
    users: 'User Access & Roles',
    settings: 'System Settings',
    help: 'Help Center',
    logout: 'Sign Out',
    main_menu: 'Main Navigation',
    enterprise_automation: 'Enterprise Automation',

    // Dashboard Page
    executive_dashboard: 'Executive Dashboard',
    smart_control: 'Smart Automation',
    realtime_overview: 'Real-time overview of global manufacturing operations & inventory.',
    refresh: 'Sync Live Data',
    sync_data: 'Sync Data',

    // Header & Quick Actions
    search_placeholder: 'Search operations, products, logs...',
    export: 'Export Data',
    new_action: 'Quick Action',
    add_new_product: '+ Add New Product',
    record_production: 'Record Production',
    record_stock_out: 'Record Stock Out',

    // KPI Summary Cards
    total_products: 'Total Products',
    today_production: "Today's Production",
    current_inventory: 'Current Stock Level',
    low_stock_alerts: 'Low Stock Alerts',
    production_efficiency: 'Line Efficiency (OEE)',
    active_catalog: 'Active catalog items',
    vs_daily_target: 'vs daily target',
    total_items_in_stock: 'Total items in stock',
    require_attention: 'Items require attention',
    optimal_output: 'Optimal line output',

    // Dashboard widgets
    recent_activity: 'Live Production Stream',
    stock_status: 'Inventory Levels & Safety',
    quick_stats: 'Operational Summary',
    view_all_logs: 'View Complete Audit Logs',
    manage_inventory: 'Open Inventory Management',

    // Stock levels
    in_stock: 'In Stock',
    low_stock: 'Low Stock',
    out_of_stock: 'Critical',
    units_left: 'units remaining',

    // Forms and Modals
    add_product_title: 'Create Catalog Product',
    edit_product_title: 'Modify Catalog Product',
    product_name: 'Product Name',
    unit: 'Unit of Measure',
    min_stock: 'Safety Stock Threshold',
    current_stock: 'Current Stock Quantity',
    save_product: 'Save Product',
    saving: 'Processing...',
    confirm_delete: 'Are you sure you want to delete this record?',
    confirm_delete_product: 'Are you sure you want to delete product',
    delete_product_success: 'Product deleted from master catalog successfully.',
    delete_warning: 'This action is irreversible and will remove associated telemetry logs.',

    // Common
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back to Dashboard',
    sign_in: 'Sign In to Control Center',
    username: 'Username / Operator ID',
    password: 'Password',
    login: 'Authenticate Session',
    logging_in: 'Authenticating...',
    login_subtitle: 'Enter your credentials to access industrial control systems.',

    // Settings Module Full Localization
    system_settings: 'System Settings',
    system_config: 'Industrial Control Config',
    settings_description: 'Manage platform preferences, security, notification rules, and industrial system connectivity.',
    search_settings: 'Search settings...',
    language: 'Language',
    select_language: 'Interface Language',
    language_subtitle: 'Select your preferred language for the industrial control dashboard.',
    preview_format: 'Live Format Preview',
    appearance: 'Visual Appearance',
    appearance_subtitle: 'Customize theme contrast, interface density, and visual telemetry styling.',
    theme: 'Theme Mode',
    theme_dark: 'Forge Dark (Recommended for Control Rooms)',
    theme_light: 'Clean Slate Light',
    high_contrast: 'High Contrast Mode',
    high_contrast_desc: 'Enhances visibility in high-glare or industrial factory floor environments.',
    ui_density: 'Interface Density',
    density_comfortable: 'Comfortable (Standard Touch/Desktop)',
    density_compact: 'Compact (High-Density Telemetry)',
    accent_color: 'Telemetry Accent Color',
    accent_blue: 'Forge Blue',
    accent_emerald: 'Emerald Automation',
    accent_amber: 'Cyber Amber',
    accent_violet: 'Tech Violet',
    profile: 'User Profile',
    profile_info: 'Operator Profile & Identity',
    profile_subtitle: 'Manage your operator identity, contact details, and factory terminal preferences.',
    full_name: 'Full Name',
    department: 'Department / Unit',
    job_title: 'Job Title',
    phone_number: 'Contact Phone',
    timezone: 'Terminal Timezone',
    save_profile: 'Save Profile Changes',
    profile_updated: 'Profile preferences updated successfully.',
    security: 'Security & Access',
    security_title: 'Security & Authentication',
    security_subtitle: 'Manage authentication credentials, two-factor verification, and active workstations.',
    update_password: 'Update Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    password_updated: 'Password has been updated successfully.',
    two_factor_auth: 'Two-Factor Authentication (2FA)',
    two_factor_desc: 'Enforce hardware security key or TOTP authenticator app for critical control actions.',
    two_factor_status_active: '2FA is Active & Protected',
    two_factor_status_inactive: '2FA Inactive (Disabled)',
    two_factor_setup_btn: 'Configure 2FA',
    two_factor_disable_btn: 'Disable 2FA',
    two_factor_modal_title: 'Two-Factor Authentication Setup (TOTP)',
    two_factor_step_1: '1. Scan QR Code in Authenticator App',
    two_factor_step_1_desc: 'Scan this QR code with Google Authenticator, Microsoft Authenticator, Apple Passwords, or 1Password.',
    two_factor_manual_key: 'Manual Secret Key',
    two_factor_copy_key: 'Copy Key',
    two_factor_copied: 'Copied!',
    two_factor_step_2: '2. Save Emergency Recovery Codes',
    two_factor_step_2_desc: 'Save these 8 single-use recovery codes in a safe place. You can use them to log in if you lose your device.',
    two_factor_step_3: '3. Verify 6-Digit TOTP Code',
    two_factor_verify_btn: 'Verify & Activate 2FA',
    two_factor_enabled_toast: 'Two-Factor Authentication is now active!',
    two_factor_disabled_toast: 'Two-Factor Authentication has been disabled.',
    two_factor_login_title: 'Two-Factor Authentication (2FA)',
    two_factor_login_prompt: 'Enter the 6-digit verification code from your authenticator app or enter a single-use backup recovery code.',
    two_factor_verify_login_btn: 'Verify & Sign In',
    active_sessions: 'Active Factory Workstations',
    revoke_other_sessions: 'Terminate Other Sessions',
    confirm_revoke_sessions: 'Are you sure you want to terminate all other workstation sessions?',
    session_revoked: 'All other active sessions have been terminated.',
    notifications: 'Notifications',
    notification_rules: 'Alert & Notification Rules',
    notification_rules_desc: 'Configure alert triggers, escalation thresholds, and delivery channels for shop floor events.',
    delivery_channels: 'Delivery Channels',
    channel_in_app: 'In-App Alerts',
    channel_email: 'Email Digest',
    channel_audio: 'Audible Siren Alert',
    alert_low_stock: 'Low Stock Safety Alerts',
    alert_low_stock_desc: 'Trigger alert when catalog item drops below safety minimum.',
    alert_maintenance: 'Machine Maintenance Reminders (500h)',
    alert_maintenance_desc: 'Alert operators when CNC or Press machine reaches 500 runtime hours.',
    alert_shift_batch: 'Shift Production Output Summaries',
    alert_shift_batch_desc: 'Dispatch shift output summary & inventory mutation log.',
    alert_db_sync: 'Database Sync & Latency Warnings',
    alert_db_sync_desc: 'Warn on MSSQL latency spike or telemetry polling disconnects.',
    save_notifications: 'Save Notification Rules',
    notifications_saved: 'Notification rules updated successfully.',
    help_faq: 'Help & Operational FAQ',
    system: 'Factory Operations',
    system_infra: 'Factory Operations & Infrastructure',
    system_infra_desc: 'Configure shift output targets, OEE efficiency standards, active manufacturing lines, and database snapshot backups.',
    backend_api_url: 'Backend API Gateway URL',
    mssql_db_host: 'MSSQL Database Host & Catalog',
    auto_sync_interval: 'Auto-Sync Polling Interval',
    default_export_format: 'Default Export Format',
    telemetry_log_level: 'Telemetry Log Level',
    trigger_backup: 'Trigger Manual Database Backup',
    save_preferences: 'Save Configuration',
    system_config_saved: 'Factory operations configuration saved successfully.',
    shift_output_targets: 'Shift Production Output Targets',
    target_shift_1: 'Shift 1 Target (Morning)',
    target_shift_2: 'Shift 2 Target (Afternoon)',
    target_shift_3: 'Shift 3 Target (Night)',
    oee_standard_target: 'Minimum OEE Efficiency Target',
    global_safety_stock_threshold: 'Global Safety Stock Threshold',
    factory_production_lines: 'Active Manufacturing Lines',
    line_1_name: 'Line 1 - CNC Machining & Milling',
    line_2_name: 'Line 2 - Stamping & Hydraulic Press',
    line_3_name: 'Line 3 - Final Assembly & Packaging',
    backup_retention_policy: 'Database Backup & Retention Policy',
    auto_backup_schedule: 'Automated Backup Schedule',
    backup_shift_change: 'Every Shift Changeover (8 Hours)',
    backup_daily_midnight: 'Daily at 00:00 (Midnight)',
    backup_weekly_sunday: 'Weekly on Sundays',
    save_factory_config: 'Save Factory Operations Config',

    // Table headers & Details
    product_code: 'Code',
    category: 'Category',
    stock: 'Stock',
    min: 'Min',
    shift: 'Shift',
    operator: 'Operator',
    machine_id: 'Machine ID',
    quantity: 'Quantity',
    status: 'Status',
    last_activity: 'Last Activity',
    actions: 'Actions',
    role: 'Role',
    user: 'User',
    last_login: 'Last Login',
    active_status_label: 'Active',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operator',

    // Units & Measures
    units: 'units',
    pcs: 'pcs',
    produce: 'Produce',
    view_all: 'View All',
    showing: 'Showing',
    of: 'of',
    loading: 'Loading...',

    // Timeframes & Days
    tf_7d: '7D',
    tf_30d: '30D',
    tf_ytd: 'YTD',
    days_mon: 'Mon',
    days_tue: 'Tue',
    days_wed: 'Wed',
    days_thu: 'Thu',
    days_fri: 'Fri',
    days_sat: 'Sat',
    days_sun: 'Sun',

    // Buttons
    save: 'Save Product',
    submit: 'Submit',
    view: 'View',
    interface_language: 'Interface Language',
    production_analytics: 'Production Analytics',
    production_analytics_subtitle: 'Real-time telemetry and throughput volume tracking.',
    live_output: 'Live Output',
    quick_actions: 'Quick Actions',
    quick_actions_subtitle: 'Instant factory floor control & inventory triggers.',
    add_product: 'Add Product',
    stock_out_btn: 'Record Stock Out',
    system_status: 'System Infrastructure Status',
    system_status_subtitle: 'MSSQL database connectivity, cluster latency, and runtime status.',
    all_systems_nominal: 'All Systems Nominal',
    last_sync_text: 'Automated database synchronization active',
    synced: 'Synced',
    low_stock_subtitle: 'Critical SKUs requiring immediate replenishment.',
    action_required: 'Action Required',
    out_of_stock_status: 'Out of Stock',
    low_stock_status: 'Low Stock',
    in_stock_status: 'In Stock',
    products_management: 'Products Management',
    master_catalog: 'Master Catalog',
    products_subtitle: 'Manage master product SKUs, minimum stock thresholds, and bill of materials.',
    search_products: 'Search products by name or code...',
    all_statuses: 'All Statuses',
    product_id: 'Product ID',
    no_products: 'No products found',
    production_logs_title: 'Production Logging & Execution',
    live_manufacturing_data: 'Live Factory Data',
    production_logs_subtitle: 'Record manufacturing output runs, shift assignments, and real-time inventory increases.',
    new_log_entry: 'New Production Entry',
    select_product: 'Select Product',
    operator_name: 'Operator Name',
    select_machine: 'Select Machine / Workstation',
    quantity_produced: 'Quantity Produced',
    mutation_date: 'Production Date & Time',
    submit_log: 'Submit Production Record',
    recent_logs: 'Recent Production Records',
    shift_morning: 'Morning Shift (06:00 - 14:00)',
    shift_afternoon: 'Afternoon Shift (14:00 - 22:00)',
    shift_night: 'Night Shift (22:00 - 06:00)',
    log_submitted_success: 'Production log recorded and inventory mutated successfully.',
    no_production_logs: 'No production records found.',
    time: 'Time',
    inventory_title: 'Warehouse & Inventory Operations',
    intelligence_center: 'Intelligence Center',
    inventory_subtitle: 'Monitor inventory levels, inbound/outbound movements, and stock valuation.',
    stock_operations: 'Stock Operations',
    total_warehouse_value: 'Total Warehouse Valuation',
    storage_capacity: 'Storage Capacity Utilization',
    inventory_forecast: 'Inventory Depletion Forecast',
    stock_movements: 'Stock Mutation Ledger',
    stock_movements_subtitle: 'Complete audit trail of inventory IN and OUT transactions.',
    current_stock_label: 'Current Stock',
    mutation_type: 'Mutation Type',
    zone_utilization: 'Warehouse Zone Utilization',
    from_last_month: '+2.4% from last month',
    capacity_sqft: 'sq ft',
    audit_passed: 'PASSED',
    auditor_label: 'Auditor: J. Miller',
    no_stock_movements: 'No stock movements recorded yet.',
    production_output: 'Production Output',
    warehouse_dispatch: 'Warehouse Dispatch',
    zone_capacity_desc: 'Warehouse capacity per storage sector (%)',
    capacity_used: 'Capacity Used',
    standard_storage: 'Standard Storage',
    hazmat_zone: 'Hazmat Zone',
    stock_out_note: 'Note: Request will fail if requested quantity exceeds current available stock.',
    please_select_product: 'Please select a product',
    export_inventory_success: 'Factory inventory report downloaded successfully.',
    reports_title: 'Reports & Executive Analytics',
    reports_subtitle: 'Deep analytical insights into manufacturing efficiency, stock velocity, and plant performance.',
    monthly_yield: 'Monthly Yield & Output Trends',
    monthly_yield_desc: 'Real-time aggregated output per month from MSSQL',
    top_products_distribution: 'Top Products Output Distribution',
    top_products_desc: 'Distribution by production volume',
    machine_performance_heatmap: 'Machine Fleet Performance Heatmap',
    heatmap_desc: 'Uptime and efficiency across active units (Last 24h)',
    heatmap_low: 'Low',
    heatmap_optimal: 'Optimal',
    forecast_desc: 'Predicted stock levels based on current run rate',
    timeframe_last_30_days: 'Last 30 Days',
    timeframe_last_7_days: 'Last 7 Days',
    timeframe_last_90_days: 'Last 90 Days',
    export_pdf: 'PDF',
    export_excel: 'EXCEL',
    export_csv: 'CSV',
    day_today: 'Today',
    day_prefix: 'Day',
    users_title: 'User Access & Role Management',
    access_control: 'Access Control',
    users_subtitle: 'Manage platform operators, supervisors, and administrative RBAC permissions.',
    invite_user: 'Add New User',
    add_user_title: 'Add New Platform User',
    add_user_desc: 'Create user account credentials for MSSQL database',
    user_created_success: 'User account created successfully.',
    user_updated_success: 'User role updated successfully.',
    user_deleted_success: 'User account deleted successfully.',
    manage_user: 'Manage User',
    edit_user_role: 'Change Role',
    delete_user: 'Delete User',
    confirm_delete_user: 'Are you sure you want to delete user',
    no_users_found: 'No user accounts found matching query.',
    loading_users: 'Loading user accounts...',
    all_roles: 'All Roles',
    admin_role: 'Administrator',
    admin_role_desc: 'Full system access, user management, configuration, and security settings.',
    supervisor_role: 'Supervisor',
    supervisor_role_desc: 'Can oversee production logs, manage catalog items, and view analytic reports.',
    operator_role: 'Operator',
    operator_role_desc: 'Authorized for daily production logging and stock movement records.',
    role_permissions: 'Role & Permission Definitions',
    active_status: 'Active',
    last_audit: 'Last Activity',
    online: 'Online',
    add_product_desc: 'Register a new raw material or finished product SKU in the master catalog.',
    category_electronics: 'Electronics & Automation',
    category_mechanical: 'Mechanical Parts',
    category_sensors: 'Sensors & Actuators',
    category_raw: 'Raw Materials',
    category_plcs: 'PLCs & Controllers',
    unit_of_measure: 'Unit of Measure',
    unit_pcs: 'Pieces (pcs)',
    unit_box: 'Boxes (box)',
    unit_meter: 'Meters (m)',
    unit_kg: 'Kilograms (kg)',
    initial_stock_label: 'Initial Opening Stock',
    min_stock_label: 'Minimum Stock Threshold (Safety Stock)',
    primary_supplier_label: 'Primary Supplier / Vendor',
    description: 'Product Specification & Description',
    import_csv: 'Import CSV',
    import_products_title: 'Import Products from CSV',
    import_products_desc: 'Upload a standardized CSV file to batch insert new product SKUs into master catalog.',
    download_template: 'Download CSV Template',
    drag_drop_csv: 'Click or drag & drop CSV file here',
    valid_rows_found: 'Valid rows ready for import',
    import_success: 'Products imported successfully into master catalog.',
    export_catalog_csv: 'Export Products (CSV)',
    record_daily_production: 'Record Production Log',
    record_daily_desc: 'Log newly manufactured units and instantly update live warehouse stock.',
    select_product_prompt: 'Select Product SKU',
    operator_name_label: 'Assigned Operator',
    save_production_log: 'Save & Increment Stock',
    record_stock_out_title: 'Record Stock Out Mutation',
    record_stock_out_desc: 'Deduct items from warehouse inventory for distribution or production usage.',
    quantity_deducted: 'Quantity to Deduct',
    confirm_stock_out: 'Confirm Stock Deduction',
    confirm_sign_out: 'Confirm Sign Out',
    sign_out_desc: 'Are you sure you want to end your workstation session? Any unsaved edits will be discarded.',
    active_session: 'Active Station',
    yes_sign_out: 'Yes, Sign Out',
    signing_out: 'Signing out...',
    notification_center: 'Notification Center',
    notifications_desc: 'Real-time telemetry alerts, low stock warnings, and operational events.',
    mark_all_read: 'Mark All as Read',
    all_filter: 'All',
    unread_filter: 'Unread',
    critical_filter: 'Critical',
    clear_all: 'Clear All',
    confirm_clear_notifications: 'Are you sure you want to clear all notifications?',
    no_notifications: 'No notifications to display',
    new_badge: 'NEW',
    help_center_title: 'Help Center & Documentation',
    documentation: 'Documentation',
    help_center_subtitle: 'Operational guides, standard operating procedures (SOP), and technical support.',
    quick_start_guide: 'Quick Start Guide',
    quick_start_guide_desc: 'Learn the fundamentals of dashboard navigation and workstation telemetry.',
    production_flow_guide: 'Production Flow & Logging SOP',
    production_flow_guide_desc: 'Standard procedures for entering shift logs and validating material output.',
    inventory_rules_guide: 'Inventory & Stock Safety Thresholds',
    inventory_rules_guide_desc: 'How automated alerts work when stock falls below minimum safety quantities.',
    faq_title: 'Frequently Asked Questions',
    faq_1_q: 'How do I add a new product SKU to the factory catalog?',
    faq_1_a: 'Navigate to Products Catalog, click "+ Add Product", fill in the SKU code, minimum safety threshold, and initial stock.',
    faq_2_q: 'What happens when stock falls below the minimum threshold?',
    faq_2_a: 'The system automatically flags the item in red under Low Stock Alerts and triggers an instant in-app notification.',
    faq_3_q: 'How is Two-Factor Authentication (2FA) configured?',
    faq_3_a: 'Go to System Settings > Security & Password, click "Configure 2FA", scan the QR code with your authenticator app, and enter the 6-digit code.',
    contact_support: 'Contact Technical Support',
    support_team_hours: '24/7 Factory Operations Support Desk • Extension 4040',
    open_support_ticket: 'Create Support Ticket',
    back_to_dashboard: 'Back to Executive Dashboard',
  },
  id: {
    // Navigasi & Sidebar
    dashboard: 'Dasbor Eksekutif',
    products: 'Katalog Produk',
    production_logs: 'Catatan Produksi',
    inventory: 'Inventaris & Stok',
    reports: 'Laporan & Analitik',
    users: 'Akses & Peran Pengguna',
    settings: 'Pengaturan Sistem',
    help: 'Pusat Bantuan',
    logout: 'Keluar',
    main_menu: 'Navigasi Utama',
    enterprise_automation: 'Otomasi Industri',

    // Halaman Dashboard
    executive_dashboard: 'Dasbor Eksekutif',
    smart_control: 'Otomasi Pintar',
    realtime_overview: 'Pemantauan operasional manufaktur & inventaris pabrik secara real-time.',
    refresh: 'Sinkronkan Data Live',
    sync_data: 'Sinkronkan Data',

    // Header & Quick Actions
    search_placeholder: 'Cari operasional, produk, log...',
    export: 'Ekspor Data',
    new_action: 'Aksi Cepat',
    add_new_product: '+ Tambah Produk Baru',
    record_production: 'Catat Produksi',
    record_stock_out: 'Catat Stok Keluar',

    // KPI Cards
    total_products: 'Total Produk',
    today_production: 'Produksi Hari Ini',
    current_inventory: 'Tingkat Stok Saat Ini',
    low_stock_alerts: 'Peringatan Stok Rendah',
    production_efficiency: 'Efisiensi Jalur (OEE)',
    active_catalog: 'Item katalog aktif',
    vs_daily_target: 'vs target harian',
    total_items_in_stock: 'Total item dalam stok',
    require_attention: 'Item butuh perhatian',
    optimal_output: 'Keluaran lini optimal',

    // Dashboard widgets
    recent_activity: 'Aktivitas Produksi Langsung',
    stock_status: 'Tingkat Stok & Keamanan',
    quick_stats: 'Ringkasan Operasional',
    view_all_logs: 'Lihat Semua Log Audit',
    manage_inventory: 'Buka Manajemen Stok',

    // Stock levels
    in_stock: 'Stok Aman',
    low_stock: 'Stok Menipis',
    out_of_stock: 'Kritis',
    units_left: 'unit tersisa',

    // Forms and Modals
    add_product_title: 'Tambah Produk Baru',
    edit_product_title: 'Ubah Data Produk',
    product_name: 'Nama Produk',
    unit: 'Satuan Ukuran',
    min_stock: 'Batas Minimum Stok',
    current_stock: 'Jumlah Stok Saat Ini',
    save_product: 'Simpan Produk',
    saving: 'Menyimpan...',
    confirm_delete: 'Apakah Anda yakin ingin menghapus data ini?',
    confirm_delete_product: 'Apakah Anda yakin ingin menghapus produk',
    delete_product_success: 'Produk berhasil dihapus dari katalog master.',
    delete_warning: 'Tindakan ini tidak dapat dibatalkan dan akan menghapus catatan telemetri terkait.',

    // Common
    success: 'Berhasil',
    error: 'Terjadi Kesalahan',
    warning: 'Peringatan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Ubah',
    back: 'Kembali ke Dasbor',
    sign_in: 'Masuk ke Pusat Kontrol',
    username: 'Nama Pengguna / ID Operator',
    password: 'Kata Sandi',
    login: 'Masuk ke Sistem',
    logging_in: 'Memverifikasi...',
    login_subtitle: 'Masukkan kredensial Anda untuk mengakses sistem otomasi industri.',

    // Settings Module Full Localization
    system_settings: 'Pengaturan Sistem',
    system_config: 'Konfigurasi Kontrol Industri',
    settings_description: 'Kelola preferensi platform, keamanan akun, aturan notifikasi, dan konektivitas infrastruktur pabrik.',
    search_settings: 'Cari pengaturan...',
    language: 'Bahasa',
    select_language: 'Bahasa Antarmuka',
    language_subtitle: 'Pilih bahasa antarmuka untuk panel kontrol industri.',
    preview_format: 'Pratinjau Format Langsung',
    appearance: 'Tampilan Visual',
    appearance_subtitle: 'Sesuaikan kontras tema, kepadatan antarmuka, dan gaya visual telemetri.',
    theme: 'Mode Tema',
    theme_dark: 'Forge Gelap (Disarankan untuk Ruang Kontrol)',
    theme_light: 'Clean Slate Terang',
    high_contrast: 'Mode Kontras Tinggi',
    high_contrast_desc: 'Meningkatkan keterbacaan pada area pabrik dengan pencahayaan silau atau ekstrem.',
    ui_density: 'Kepadatan Antarmuka',
    density_comfortable: 'Standar (Sentuh / Desktop Luas)',
    density_compact: 'Kompak (Telemetri Kerapatan Tinggi)',
    accent_color: 'Warna Aksen Telemetri',
    accent_blue: 'Forge Blue',
    accent_emerald: 'Emerald Automation',
    accent_amber: 'Cyber Amber',
    accent_violet: 'Tech Violet',
    profile: 'Profil Pengguna',
    profile_info: 'Profil & Identitas Operator',
    profile_subtitle: 'Kelola identitas operator, informasi kontak, dan workstation pabrik Anda.',
    full_name: 'Nama Lengkap',
    department: 'Departemen / Divisi',
    job_title: 'Jabatan / Posisi',
    phone_number: 'Nomor Telepon',
    timezone: 'Zona Waktu Terminal',
    save_profile: 'Simpan Perubahan Profil',
    profile_updated: 'Preferensi profil berhasil diperbarui.',
    security: 'Keamanan & Sandi',
    security_title: 'Keamanan & Akses Autentikasi',
    security_subtitle: 'Kelola kredensial akses, verifikasi dua langkah, dan workstation yang sedang aktif.',
    update_password: 'Perbarui Kata Sandi',
    current_password: 'Kata Sandi Saat Ini',
    new_password: 'Kata Sandi Baru',
    confirm_password: 'Konfirmasi Kata Sandi Baru',
    password_updated: 'Kata sandi berhasil diperbarui.',
    two_factor_auth: 'Autentikasi Dua Faktor (2FA)',
    two_factor_desc: 'Wajibkan kunci keamanan perangkat keras atau aplikasi TOTP untuk tindakan kritis.',
    two_factor_status_active: '2FA Aktif & Terlindungi',
    two_factor_status_inactive: '2FA Nonaktif',
    two_factor_setup_btn: 'Konfigurasi 2FA',
    two_factor_disable_btn: 'Nonaktifkan 2FA',
    two_factor_modal_title: 'Pengaturan Autentikasi Dua Faktor (TOTP)',
    two_factor_step_1: '1. Pindai QR Code di Aplikasi Authenticator',
    two_factor_step_1_desc: 'Pindai QR code ini menggunakan Google Authenticator, Microsoft Authenticator, Apple Passwords, atau 1Password.',
    two_factor_manual_key: 'Kunci Rahasia Manual',
    two_factor_copy_key: 'Salin Kunci',
    two_factor_copied: 'Tersalin!',
    two_factor_step_2: '2. Simpan Kode Pemulihan Darurat',
    two_factor_step_2_desc: 'Simpan 8 kode pemulihan sekali-pakai ini di tempat yang aman. Anda dapat menggunakannya untuk login jika perangkat hilang.',
    two_factor_step_3: '3. Verifikasi Kode TOTP 6-Digit',
    two_factor_verify_btn: 'Verifikasi & Aktifkan 2FA',
    two_factor_enabled_toast: 'Autentikasi Dua Faktor berhasil diaktifkan!',
    two_factor_disabled_toast: 'Autentikasi Dua Faktor telah dinonaktifkan.',
    two_factor_login_title: 'Verifikasi Dua Faktor (2FA)',
    two_factor_login_prompt: 'Masukkan kode verifikasi 6-digit dari aplikasi authenticator atau masukkan kode pemulihan cadangan.',
    two_factor_verify_login_btn: 'Verifikasi & Masuk',
    active_sessions: 'Sesi Workstation Aktif',
    revoke_other_sessions: 'Putuskan Sesi Lain',
    confirm_revoke_sessions: 'Apakah Anda yakin ingin memutuskan semua sesi workstation lain?',
    session_revoked: 'Semua sesi workstation lain berhasil diputuskan.',
    notifications: 'Notifikasi Sistem',
    notification_rules: 'Aturan Peringatan & Notifikasi',
    notification_rules_desc: 'Konfigurasikan ambang batas peringatan, eskalasi, dan saluran pengiriman peristiwa lantai pabrik.',
    delivery_channels: 'Saluran Pengiriman Notifikasi',
    channel_in_app: 'Peringatan Dalam Aplikasi',
    channel_email: 'Ringkasan Email',
    channel_audio: 'Peringatan Sirene Suara',
    alert_low_stock: 'Peringatan Batas Aman Stok Rendah',
    alert_low_stock_desc: 'Picu peringatan saat stok katalog berada di bawah batas aman minimum.',
    alert_maintenance: 'Peringatan Pemeliharaan Berkala Mesin (500 Jam)',
    alert_maintenance_desc: 'Peringatkan operator saat mesin CNC atau Press mencapai 500 jam kerja.',
    alert_shift_batch: 'Laporan Output Produksi Batch Shift',
    alert_shift_batch_desc: 'Kirimkan ringkasan output produksi shift & log mutasi inventaris.',
    alert_db_sync: 'Peringatan Sinkronisasi Basis Data & Latensi',
    alert_db_sync_desc: 'Beri peringatan saat latensi MSSQL melonjak atau polling terputus.',
    save_notifications: 'Simpan Aturan Notifikasi',
    notifications_saved: 'Aturan notifikasi berhasil disimpan.',
    help_faq: 'Pusat Bantuan & FAQ',
    system: 'Operasional Pabrik',
    system_infra: 'Konfigurasi Operasional & Infrastruktur',
    system_infra_desc: 'Konfigurasikan target output per shift, standar efisiensi OEE, lini produksi aktif, dan pencadangan database.',
    backend_api_url: 'URL Gateway API Backend Go',
    mssql_db_host: 'Host Basis Data & Katalog MSSQL',
    auto_sync_interval: 'Interval Sinkronisasi Otomatis',
    default_export_format: 'Format Standar Ekspor',
    telemetry_log_level: 'Tingkat Pencatatan Log Telemetri',
    trigger_backup: 'Jalankan Pencadangan Database Manual',
    save_preferences: 'Simpan Konfigurasi',
    system_config_saved: 'Konfigurasi operasional pabrik berhasil disimpan.',
    shift_output_targets: 'Target Output Produksi per Shift',
    target_shift_1: 'Target Shift 1 (Pagi)',
    target_shift_2: 'Target Shift 2 (Siang)',
    target_shift_3: 'Target Shift 3 (Malam)',
    oee_standard_target: 'Target Efisiensi OEE Minimum',
    global_safety_stock_threshold: 'Batas Minimum Safety Stock Global',
    factory_production_lines: 'Lini Manufaktur Aktif',
    line_1_name: 'Lini 1 - CNC Machining & Milling',
    line_2_name: 'Lini 2 - Stamping & Hydraulic Press',
    line_3_name: 'Lini 3 - Final Assembly & Packaging',
    backup_retention_policy: 'Pencadangan Basis Data & Retensi',
    auto_backup_schedule: 'Jadwal Pencadangan Otomatis',
    backup_shift_change: 'Setiap Pergantian Shift (8 Jam)',
    backup_daily_midnight: 'Harian (Pukul 00:00 WIB)',
    backup_weekly_sunday: 'Mingguan (Setiap Hari Minggu)',
    save_factory_config: 'Simpan Konfigurasi Operasional',

    // Table headers
    product_code: 'Kode',
    category: 'Kategori',
    stock: 'Stok',
    min: 'Min',
    shift: 'Giliran (Shift)',
    operator: 'Operator',
    machine_id: 'ID Mesin',
    quantity: 'Jumlah',
    status: 'Status',
    last_activity: 'Aktivitas Terakhir',
    actions: 'Aksi',
    role: 'Peran',
    user: 'Pengguna',
    last_login: 'Login Terakhir',
    active_status_label: 'Aktif',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operator',

    // Units & Measures
    units: 'unit',
    pcs: 'pcs',
    produce: 'Produksi',
    view_all: 'Lihat Semua',
    showing: 'Menampilkan',
    of: 'dari',
    loading: 'Memuat...',

    // Timeframes & Days
    tf_7d: '7H',
    tf_30d: '30H',
    tf_ytd: 'YTD',
    days_mon: 'Sen',
    days_tue: 'Sel',
    days_wed: 'Rab',
    days_thu: 'Kam',
    days_fri: 'Jum',
    days_sat: 'Sab',
    days_sun: 'Min',

    // Buttons
    save: 'Simpan Produk',
    submit: 'Kirim',
    view: 'Lihat',
    interface_language: 'Bahasa Antarmuka',
    production_analytics: 'Analisis Hasil Produksi',
    production_analytics_subtitle: 'Telemetri real-time dan pemantauan volume output manufaktur.',
    live_output: 'Keluaran Langsung',
    quick_actions: 'Aksi Cepat',
    quick_actions_subtitle: 'Akses cepat kendali lantai pabrik & mutasi inventaris.',
    add_product: 'Tambah Produk',
    stock_out_btn: 'Catat Stok Keluar',
    system_status: 'Status Infrastruktur Sistem',
    system_status_subtitle: 'Konektivitas database MSSQL, latensi cluster, dan status runtime.',
    all_systems_nominal: 'Semua Sistem Beroperasi Normal',
    last_sync_text: 'Sinkronisasi database otomatis aktif',
    synced: 'Tersinkron',
    low_stock_subtitle: 'SKU kritis yang memerlukan pengadaan atau produksi segera.',
    action_required: 'Perlu Tindakan',
    out_of_stock_status: 'Stok Habis',
    low_stock_status: 'Stok Rendah',
    in_stock_status: 'Stok Tersedia',
    products_management: 'Manajemen Katalog Produk',
    master_catalog: 'Katalog Utama',
    products_subtitle: 'Kelola master SKU produk, ambang batas minimum stok, dan spesifikasi material.',
    search_products: 'Cari produk berdasarkan nama atau kode...',
    all_statuses: 'Semua Status',
    product_id: 'ID Produk',
    no_products: 'Tidak ada produk yang ditemukan',
    production_logs_title: 'Pencatatan & Eksekusi Produksi',
    live_manufacturing_data: 'Data Pabrik Langsung',
    production_logs_subtitle: 'Catat output lini perakitan manufaktur, shift kerja, dan penambahan inventaris otomatis.',
    new_log_entry: 'Entri Catatan Produksi Baru',
    select_product: 'Pilih Produk',
    operator_name: 'Nama Operator',
    select_machine: 'Pilih Mesin / Workstation',
    quantity_produced: 'Jumlah yang Diproduksi',
    mutation_date: 'Waktu & Tanggal Produksi',
    submit_log: 'Simpan Catatan Produksi',
    recent_logs: 'Catatan Riwayat Produksi Terbaru',
    shift_morning: 'Shift Pagi (06:00 - 14:00)',
    shift_afternoon: 'Shift Siang (14:00 - 22:00)',
    shift_night: 'Shift Malam (22:00 - 06:00)',
    log_submitted_success: 'Catatan produksi berhasil disimpan dan mutasi stok diperbarui.',
    no_production_logs: 'Belum ada catatan riwayat produksi.',
    time: 'Waktu',
    inventory_title: 'Operasi Inventaris & Pergudangan',
    intelligence_center: 'Pusat Analisis',
    inventory_subtitle: 'Pantau ketersediaan stok fisik, mutasi masuk/keluar, dan estimasi valuasi gudang.',
    stock_operations: 'Operasi Mutasi Stok',
    total_warehouse_value: 'Total Estimasi Valuasi Gudang',
    storage_capacity: 'Utilisasi Kapasitas Penyimpanan',
    inventory_forecast: 'Prakiraan Pengurangan Stok',
    stock_movements: 'Buku Log Mutasi Stok',
    stock_movements_subtitle: 'Jejak audit lengkap transaksi inventaris MASUK (IN) dan KELUAR (OUT).',
    current_stock_label: 'Stok Saat Ini',
    mutation_type: 'Tipe Mutasi',
    zone_utilization: 'Utilisasi Zona Rak Gudang',
    from_last_month: '+2.4% dari bulan lalu',
    capacity_sqft: 'sq ft',
    audit_passed: 'LOLOS',
    auditor_label: 'Auditor: J. Miller',
    no_stock_movements: 'Belum ada catatan mutasi stok tersimpan.',
    production_output: 'Keluaran Produksi',
    warehouse_dispatch: 'Pengeluaran Gudang',
    zone_capacity_desc: 'Kapasitas gudang per sektor penyimpanan (%)',
    capacity_used: 'Kapasitas Terpakai',
    standard_storage: 'Penyimpanan Standar',
    hazmat_zone: 'Zona Khusus / Hazmat',
    stock_out_note: 'Catatan: Permintaan akan ditolak jika jumlah melebihi stok yang tersedia.',
    please_select_product: 'Silakan pilih produk',
    export_inventory_success: 'Laporan inventaris pabrik berhasil diunduh.',
    reports_title: 'Laporan & Analisis Eksekutif',
    reports_subtitle: 'Wawasan analitis mendalam mengenai efisiensi manufaktur, perputaran stok, dan kinerja pabrik.',
    monthly_yield: 'Tren Hasil Produksi Bulanan',
    monthly_yield_desc: 'Keluaran agregat per bulan real-time dari MSSQL',
    top_products_distribution: 'Distribusi Keluaran Produk Unggulan',
    top_products_desc: 'Distribusi berdasarkan volume produksi',
    machine_performance_heatmap: 'Peta Kinerja Armada Mesin',
    heatmap_desc: 'Uptime dan efisiensi di seluruh unit aktif (24 Jam Terakhir)',
    heatmap_low: 'Rendah',
    heatmap_optimal: 'Optimal',
    forecast_desc: 'Prakiraan tingkat stok berdasarkan laju pemakaian saat ini',
    timeframe_last_30_days: '30 Hari Terakhir',
    timeframe_last_7_days: '7 Hari Terakhir',
    timeframe_last_90_days: '90 Hari Terakhir',
    export_pdf: 'PDF',
    export_excel: 'EXCEL',
    export_csv: 'CSV',
    day_today: 'Hari Ini',
    day_prefix: 'Hari',
    users_title: 'Manajemen Pengguna & Hak Akses',
    access_control: 'Kontrol Akses',
    users_subtitle: 'Kelola hak akses operator, supervisor, dan otorisasi RBAC administrator sistem.',
    invite_user: 'Tambah Pengguna Baru',
    add_user_title: 'Tambah Pengguna Sistem Baru',
    add_user_desc: 'Buat kredensial akun pengguna untuk basis data MSSQL',
    user_created_success: 'Akun pengguna baru berhasil dibuat.',
    user_updated_success: 'Peran pengguna berhasil diperbarui.',
    user_deleted_success: 'Akun pengguna berhasil dihapus.',
    manage_user: 'Kelola Pengguna',
    edit_user_role: 'Ubah Peran',
    delete_user: 'Hapus Pengguna',
    confirm_delete_user: 'Apakah Anda yakin ingin menghapus akun pengguna',
    no_users_found: 'Tidak ada akun pengguna yang sesuai dengan pencarian.',
    loading_users: 'Memuat akun pengguna...',
    all_roles: 'Semua Peran',
    admin_role: 'Administrator',
    admin_role_desc: 'Akses penuh ke seluruh sistem, manajemen pengguna, konfigurasi, dan keamanan.',
    supervisor_role: 'Supervisor',
    supervisor_role_desc: 'Dapat meninjau log produksi, mengelola katalog produk, dan melihat laporan analitik.',
    operator_role: 'Operator',
    operator_role_desc: 'Diberi wewenang untuk input data harian produksi dan pencatatan mutasi stok.',
    role_permissions: 'Definisi Peran & Hak Akses',
    active_status: 'Aktif',
    last_audit: 'Aktivitas Terakhir',
    online: 'Online',
    add_product_desc: 'Daftarkan SKU bahan baku atau barang jadi baru ke dalam katalog master.',
    category_electronics: 'Elektronik & Otomasi',
    category_mechanical: 'Komponen Mekanikal',
    category_sensors: 'Sensor & Aktuator',
    category_raw: 'Bahan Baku Mentah',
    category_plcs: 'PLC & Kontroler Industri',
    unit_of_measure: 'Satuan Unit Ukur',
    unit_pcs: 'Pcs / Buah (pcs)',
    unit_box: 'Kotak / Kardus (box)',
    unit_meter: 'Meter (m)',
    unit_kg: 'Kilogram (kg)',
    initial_stock_label: 'Jumlah Stok Awal',
    min_stock_label: 'Ambang Batas Minimum Stok (Safety Stock)',
    primary_supplier_label: 'Pemasok / Vendor Utama',
    description: 'Deskripsi & Spesifikasi Produk',
    import_csv: 'Impor CSV',
    import_products_title: 'Impor Katalog Produk dari CSV',
    import_products_desc: 'Unggah file CSV terstandarisasi untuk menambah SKU produk baru ke katalog master secara massal.',
    download_template: 'Unduh Templat CSV',
    drag_drop_csv: 'Klik atau seret & lepas file CSV di sini',
    valid_rows_found: 'Baris data valid siap diimpor',
    import_success: 'Produk berhasil diimpor ke dalam katalog master.',
    export_catalog_csv: 'Ekspor Katalog (CSV)',
    record_daily_production: 'Catat Produksi Harian',
    record_daily_desc: 'Catat unit yang selesai diproduksi dan perbarui stok gudang secara otomatis.',
    select_product_prompt: 'Pilih SKU Produk',
    operator_name_label: 'Operator yang Bertugas',
    save_production_log: 'Simpan & Tambah Stok',
    record_stock_out_title: 'Catat Pengeluaran Stok (Stock Out)',
    record_stock_out_desc: 'Kurangi item dari inventaris gudang untuk pengiriman atau penggunaan lini pabrik.',
    quantity_deducted: 'Jumlah yang Dikeluarkan',
    confirm_stock_out: 'Konfirmasi Pengeluaran Stok',
    confirm_sign_out: 'Konfirmasi Keluar Akun',
    sign_out_desc: 'Apakah Anda yakin ingin mengakhiri sesi workstation ini? Perubahan yang belum disimpan akan hilang.',
    active_session: 'Sesi Stasiun Aktif',
    yes_sign_out: 'Ya, Keluar Akun',
    signing_out: 'Mengeluarkan akun...',
    notification_center: 'Pusat Notifikasi',
    notifications_desc: 'Peringatan telemetri real-time, batas stok rendah, dan peristiwa operasional.',
    mark_all_read: 'Tandai Semua Sudah Dibaca',
    all_filter: 'Semua',
    unread_filter: 'Belum Dibaca',
    critical_filter: 'Kritis',
    clear_all: 'Bersihkan Semua',
    confirm_clear_notifications: 'Apakah Anda yakin ingin menghapus semua notifikasi?',
    no_notifications: 'Tidak ada notifikasi saat ini',
    new_badge: 'BARU',
    help_center_title: 'Pusat Bantuan & Dokumentasi',
    documentation: 'Dokumentasi',
    help_center_subtitle: 'Panduan operasional, prosedur standar pabrik (SOP), dan dukungan teknis.',
    quick_start_guide: 'Panduan Memulai Cepat',
    quick_start_guide_desc: 'Pelajari dasar navigasi dasbor eksekutif dan telemetri workstation lantai pabrik.',
    production_flow_guide: 'SOP Alur & Pencatatan Produksi',
    production_flow_guide_desc: 'Prosedur standar penginputan log shift kerja dan validasi output material.',
    inventory_rules_guide: 'Panduan Inventaris & Batas Safety Stock',
    inventory_rules_guide_desc: 'Cara kerja notifikasi otomatis saat stok turun di bawah batas aman minimum.',
    faq_title: 'Pertanyaan yang Sering Diajukan (FAQ)',
    faq_1_q: 'Bagaimana cara menambahkan SKU produk baru ke katalog pabrik?',
    faq_1_a: 'Buka menu Katalog Produk, klik "+ Tambah Produk", isi kode SKU, batas safety stock, dan jumlah awal.',
    faq_2_q: 'Apa yang terjadi jika jumlah stok turun di bawah batas minimum?',
    faq_2_a: 'Sistem secara otomatis menandai item berwarna merah di Peringatan Stok Rendah dan mengirim notifikasi peringatan.',
    faq_3_q: 'Bagaimana cara mengaktifkan Autentikasi Dua Faktor (2FA)?',
    faq_3_a: 'Buka Pengaturan Sistem > Keamanan & Sandi, klik "Konfigurasi 2FA", pindai QR Code dengan aplikasi authenticator, dan masukkan kode 6-digit.',
    contact_support: 'Hubungi Tim Dukungan Teknis',
    support_team_hours: 'Layanan Dukungan Operasional Pabrik 24/7 • Ekstensi 4040',
    open_support_ticket: 'Buat Tiket Bantuan',
    back_to_dashboard: 'Kembali ke Dasbor Eksekutif',
  },
  ar: {
    // Navigation & Sidebar
    dashboard: 'لوحة التحكم التنفيذية',
    products: 'كتالوج المنتجات',
    production_logs: 'سجلات الإنتاج',
    inventory: 'المخزون والمستودع',
    reports: 'التقارير والتحليلات',
    users: 'صلاحيات وأدوار المستخدمين',
    settings: 'إعدادات النظام',
    help: 'مركز المساعدة',
    logout: 'تسجيل الخروج',
    main_menu: 'القائمة الرئيسية',
    enterprise_automation: 'الأتمتة الصناعية',

    // Dashboard Page
    executive_dashboard: 'لوحة التحكم التنفيذية',
    smart_control: 'التحكم الذكي',
    realtime_overview: 'نظرة عامة ومباشرة على عمليات التصنيع والمخزون في الوقت الفعلي.',
    refresh: 'تحديث البيانات المباشرة',
    sync_data: 'مزامنة البيانات',

    // Header & Quick Actions
    search_placeholder: 'ابحث في العمليات، المنتجات، السجلات...',
    export: 'تصدير البيانات',
    new_action: 'إجراء سريع',
    add_new_product: '+ إضافة منتج جديد',
    record_production: 'تسجيل إنتاج',
    record_stock_out: 'تسجيل صرف مخزون',

    // KPI Summary Cards
    total_products: 'إجمالي المنتجات',
    today_production: 'إنتاج اليوم',
    current_inventory: 'مستوى المخزون الحالي',
    low_stock_alerts: 'تنبيهات انخفاض المخزون',
    production_efficiency: 'كفاءة الخط (OEE)',
    active_catalog: 'عناصر الكتالوج النشطة',
    vs_daily_target: 'مقارنة بالهدف اليومي',
    total_items_in_stock: 'إجمالي العناصر بالمستودع',
    require_attention: 'عناصر تتطلب تدخلاً',
    optimal_output: 'إنتاجية الخط المثالية',

    // Dashboard widgets
    recent_activity: 'بث الإنتاج المباشر',
    stock_status: 'مستويات المخزون والسلامة',
    quick_stats: 'ملخص العمليات التشغيلية',
    view_all_logs: 'عرض كامل سجلات التدقيق',
    manage_inventory: 'فتح إدارة المخزون',

    // Stock levels
    in_stock: 'متوفر وآمن',
    low_stock: 'مخزون منخفض',
    out_of_stock: 'مستوى حرج',
    units_left: 'وحدة متبقية',

    // Forms and Modals
    add_product_title: 'إضافة منتج جديد للكتالوج',
    edit_product_title: 'تعديل بيانات المنتج',
    product_name: 'اسم المنتج',
    unit: 'وحدة القياس',
    min_stock: 'حد المخزون الآمن',
    current_stock: 'كمية المخزون الحالية',
    save_product: 'حفظ المنتج',
    saving: 'جاري الحفظ...',
    confirm_delete: 'هل أنت متأكد من حذف هذا السجل؟',
    confirm_delete_product: 'هل أنت متأكد أنك تريد حذف المنتج',
    delete_product_success: 'تم حذف المنتج من الكتالوج الرئيسي بنجاح.',
    delete_warning: 'لا يمكن التراجع عن هذا الإجراء وسيتم حذف سجلات القياس المرتبطة به نهائياً.',

    // Common
    success: 'تم بنجاح',
    error: 'حدث خطأ',
    warning: 'تحذير',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    back: 'العودة إلى لوحة التحكم',
    sign_in: 'تسجيل الدخول إلى مركز التحكم',
    username: 'اسم المستخدم / معرّف المشغل',
    password: 'كلمة المرور',
    login: 'توثيق الجلسة',
    logging_in: 'جاري التحقق...',
    login_subtitle: 'أدخل بيانات الاعتماد الخاصة بك للوصول إلى أنظمة التحكم الصناعية.',

    // Settings Module Full Localization
    system_settings: 'إعدادات النظام',
    system_config: 'تكوين التحكم الصناعي',
    settings_description: 'إدارة تفضيلات المنصة والأمان وقواعد التنبيهات والاتصال بالبنية التحتية.',
    search_settings: 'البحث في الإعدادات...',
    language: 'اللغة',
    select_language: 'لغة الواجهة',
    language_subtitle: 'حدد اللغة المفضلة للوحة التحكم الصناعية.',
    preview_format: 'معاينة التنسيق المباشر',
    appearance: 'المظهر المرئي',
    appearance_subtitle: 'تخصيص تباين السمة وكثافة الواجهة ونمط القياس عن بُعد.',
    theme: 'وضع السمة',
    theme_dark: 'فورج داكن (موصى به لغرف التحكم)',
    theme_light: 'لوح فاتح نظيف',
    high_contrast: 'وضع التباين العالي',
    high_contrast_desc: 'يعزز الوضوح في بيئات المصانع ذات الإضاءة الساطعة أو المعاكسة.',
    ui_density: 'كثافة الواجهة',
    density_comfortable: 'مريح (قياسي للمس / المكتبي)',
    density_compact: 'مدمج (لقياسات عالية الكثافة)',
    accent_color: 'لون تمييز القياس عن بُعد',
    accent_blue: 'أزرق صناعي (Forge Blue)',
    accent_emerald: 'زمردي للأتمتة',
    accent_amber: 'كهرماني سيبراني',
    accent_violet: 'بنفسجي تقني',
    profile: 'ملف المستخدم',
    profile_info: 'الملف الشخصي وهوية المشغل',
    profile_subtitle: 'إدارة هويتك التشغيلية ومعلومات الاتصال ومحطة العمل الخاصة بك.',
    full_name: 'الاسم الكامل',
    department: 'القسم / الوحدة',
    job_title: 'المسمى الوظيفي',
    phone_number: 'رقم هاتف الاتصال',
    timezone: 'المنطقة الزمنية للمحطة',
    save_profile: 'حفظ تغييرات الملف الشخصي',
    profile_updated: 'تم تحديث تفضيلات الملف الشخصي بنجاح.',
    security: 'الأمان والوصول',
    security_title: 'الأمان والوصول والمصادقة',
    security_subtitle: 'إدارة بيانات الاعتماد والمصادقة الثنائية ومحطات العمل النشطة.',
    update_password: 'تحديث كلمة المرور',
    current_password: 'كلمة المرور الحالية',
    new_password: 'كلمة المرور الجديدة',
    confirm_password: 'تأكيد كلمة المرور الجديدة',
    password_updated: 'تم تحديث كلمة المرور بنجاح.',
    two_factor_auth: 'المصادقة الثنائية (2FA)',
    two_factor_desc: 'فرض مفتاح أمان مادي أو تطبيق TOTP للإجراءات الحساسة في المصنع.',
    two_factor_status_active: 'المصادقة الثنائية مفعلة ومحمية',
    two_factor_status_inactive: 'المصادقة الثنائية غير مفعلة',
    two_factor_setup_btn: 'تهيئة 2FA',
    two_factor_disable_btn: 'تعطيل المصادقة الثنائية',
    two_factor_modal_title: 'إعداد المصادقة الثنائية (TOTP)',
    two_factor_step_1: '١. امسح رمز الاستجابة السريعة في تطبيق المصادقة',
    two_factor_step_1_desc: 'امسح رمز الاستجابة السريعة هذا باستخدام Google Authenticator أو Microsoft Authenticator أو Apple Passwords.',
    two_factor_manual_key: 'المفتاح السري اليدوي',
    two_factor_copy_key: 'نسخ المفتاح',
    two_factor_copied: 'تم النسخ!',
    two_factor_step_2: '٢. حفظ رموز الاسترداد في حالات الطوارئ',
    two_factor_step_2_desc: 'احفظ رموز الاسترداد الـ 8 هذه في مكان آمن. يمكنك استخدامها لتسجيل الدخول إذا فقدت جهازك.',
    two_factor_step_3: '٣. تحقق من رمز TOTP المكون من 6 أرقام',
    two_factor_verify_btn: 'تحقق وتفعيل المصادقة الثنائية',
    two_factor_enabled_toast: 'تم تفعيل المصادقة الثنائية بنجاح!',
    two_factor_disabled_toast: 'تم تعطيل المصادقة الثنائية.',
    two_factor_login_title: 'المصادقة الثنائية (2FA)',
    two_factor_login_prompt: 'أدخل رمز التحقق المكون من 6 أرقام من تطبيق المصادقة أو رمز الاسترداد الاحتياطي.',
    two_factor_verify_login_btn: 'تحقق وتسجيل الدخول',
    active_sessions: 'محطات عمل المصنع النشطة',
    revoke_other_sessions: 'إنهاء الجلسات الأخرى',
    confirm_revoke_sessions: 'هل أنت متأكد من رغبتك في إنهاء جميع جلسات محطات العمل الأخرى؟',
    session_revoked: 'تم إنهاء جميع الجلسات الأخرى بنجاح.',
    notifications: 'الإشعارات والتنبيهات',
    notification_rules: 'قواعد التنبيهات والإشعارات',
    notification_rules_desc: 'تكوين مشغلات التنبيه، وعتبات التصعيد، وقنوات التسليم لأحداث صالة المصنع.',
    delivery_channels: 'قنوات تسليم التنبيهات',
    channel_in_app: 'تنبيهات داخل التطبيق',
    channel_email: 'ملخص البريد الإلكتروني',
    channel_audio: 'تنبيه صفارة إنذار صوتي',
    alert_low_stock: 'تنبيهات أمان انخفاض المخزون',
    alert_low_stock_desc: 'إطلاق تنبيه عندما ينخفض مخزون الصنف عن الحد الأدنى للسلامة.',
    alert_maintenance: 'تذكيرات صيانة الماكينات الدورية (٥٠٠ ساعة)',
    alert_maintenance_desc: 'تنبيه المشغلين عندما تصل ماكينات CNC أو المكابس إلى 500 ساعة تشغيل.',
    alert_shift_batch: 'ملخصات مخرجات إنتاج نوبة العمل',
    alert_shift_batch_desc: 'إرسال ملخص مخرجات الوردية وسجل حركات المخزون.',
    alert_db_sync: 'تحذيرات مزامنة قاعدة البيانات وزمن الوصول',
    alert_db_sync_desc: 'تحذير عند ارتفاع زمن وصول MSSQL أو انقطاع اتصال القياس عن بُعد.',
    save_notifications: 'حفظ قواعد الإشعارات',
    notifications_saved: 'تم تحديث قواعد الإشعارات بنجاح.',
    help_faq: 'مركز المساعدة والأسئلة الشائعة',
    system: 'عمليات المصنع',
    system_infra: 'تكوين عمليات المصنع والبنية التحتية',
    system_infra_desc: 'تكوين أهداف الإنتاج للنوبات، ومعايير الكفاءة OEE، وخطوط التصنيع، والنسخ الاحتياطي لقاعدة البيانات.',
    backend_api_url: 'عنوان URL لبوابة Go الخلفية',
    mssql_db_host: 'مضيف وكتالوج قاعدة بيانات MSSQL',
    auto_sync_interval: 'فاصل الاستقصاء للمزامنة التلقائية',
    default_export_format: 'تنسيق التصدير الافتراضي',
    telemetry_log_level: 'مستوى تسجيل القياس عن بُعد',
    trigger_backup: 'تشغيل النسخ الاحتياطي اليدوي لقاعدة البيانات',
    save_preferences: 'حفظ التكوين',
    system_config_saved: 'تم حفظ تكوين عمليات المصنع بنجاح.',
    shift_output_targets: 'أهداف إنتاج الورديات',
    target_shift_1: 'هدف الوردية الأولى (صباحاً)',
    target_shift_2: 'هدف الوردية الثانية (ظهراً)',
    target_shift_3: 'هدف الوردية الثالثة (ليلاً)',
    oee_standard_target: 'الحد الأدنى لكفاءة OEE',
    global_safety_stock_threshold: 'الحد الأدنى لمخزون الأمان العام',
    factory_production_lines: 'خطوط التصنيع النشطة',
    line_1_name: 'الخط 1 - التصنيع والتفريز CNC',
    line_2_name: 'الخط 2 - الختم والضغط الهيدروليكي',
    line_3_name: 'الخط 3 - التجميع النهائي والتغليف',
    backup_retention_policy: 'النسخ الاحتياطي وسياسة الاحتفاظ',
    auto_backup_schedule: 'جدول النسخ الاحتياطي التلقائي',
    backup_shift_change: 'عند كل تغيير وردية (8 ساعات)',
    backup_daily_midnight: 'يومياً عند منتصف الليل (00:00)',
    backup_weekly_sunday: 'أسبوعياً كل يوم أحد',
    save_factory_config: 'حفظ تكوين عمليات المصنع',

    // Table headers & Details
    product_code: 'الرمز',
    category: 'الفئة',
    stock: 'المخزون',
    min: 'الحد الأدنى',
    shift: 'وردية العمل',
    operator: 'المشغل',
    machine_id: 'معرّف الماكينة',
    quantity: 'الكمية',
    status: 'الحالة',
    last_activity: 'آخر نشاط',
    actions: 'الإجراءات',
    role: 'الدور',
    user: 'المستخدم',
    last_login: 'آخر دخول',
    active_status_label: 'نشط',
    admin: 'مسؤول',
    supervisor: 'مشرف',
    operator_text: 'مشغل',

    // Units & Measures
    units: 'وحدات',
    pcs: 'قطعة',
    produce: 'إنتاج',
    view_all: 'عرض الكل',
    showing: 'عرض',
    of: 'من أصل',
    loading: 'جاري التحميل...',

    // Timeframes & Days
    tf_7d: '٧ أيام',
    tf_30d: '٣٠ يوماً',
    tf_ytd: 'منذ بداية العام',
    days_mon: 'الإثنين',
    days_tue: 'الثلاثاء',
    days_wed: 'الأربعاء',
    days_thu: 'الخميس',
    days_fri: 'الجمعة',
    days_sat: 'السبت',
    days_sun: 'الأحد',

    // Buttons
    save: 'حفظ المنتج',
    submit: 'إرسال',
    view: 'عرض',
    interface_language: 'لغة الواجهة',
    production_analytics: 'تحليلات الإنتاج',
    production_analytics_subtitle: 'القياس المباشر عن بعد وتتبع حجم مخرجات التصنيع.',
    live_output: 'مخرجات مباشرة',
    quick_actions: 'إجراءات سريعة',
    quick_actions_subtitle: 'تحكم فوري بأرضية المصنع ومحفزات المخزون.',
    add_product: 'إضافة منتج',
    stock_out_btn: 'تسجيل خروج المخزون',
    system_status: 'حالة البنية التحتية للنظام',
    system_status_subtitle: 'اتصال قاعدة بيانات MSSQL، زمن استجابة الكتلة، وحالة التشغيل.',
    all_systems_nominal: 'جميع الأنظمة تعمل بكفاءة',
    last_sync_text: 'مزامنة قاعدة البيانات التلقائية نشطة',
    synced: 'متزامن',
    low_stock_subtitle: 'عناصر المخزون الحرجة التي تتطلب تجديداً فورياً.',
    action_required: 'مطلوب اتخاذ إجراء',
    out_of_stock_status: 'نفد المخزون',
    low_stock_status: 'مخزون منخفض',
    in_stock_status: 'متوفر في المخزون',
    products_management: 'إدارة كتالوج المنتجات',
    master_catalog: 'الكتالوج الرئيسي',
    products_subtitle: 'إدارة أصناف المنتجات الرئيسية، حدود المخزون الدنيا، وقوائم المواد.',
    search_products: 'البحث عن المنتجات بالاسم أو الرمز...',
    all_statuses: 'جميع الحالات',
    product_id: 'معرف المنتج',
    no_products: 'لم يتم العثور على منتجات',
    production_logs_title: 'تسجيل وتنفيذ الإنتاج',
    live_manufacturing_data: 'بيانات المصنع المباشرة',
    production_logs_subtitle: 'تسجيل مخرجات خطوط التصنيع وتعيينات الورديات وزيادات المخزون التلقائية.',
    new_log_entry: 'إدخال إنتاج جديد',
    select_product: 'حدد المنتج',
    operator_name: 'اسم المشغل',
    select_machine: 'حدد الماكينة / محطة العمل',
    quantity_produced: 'الكمية المنتجة',
    mutation_date: 'وقت وتاريخ الإنتاج',
    submit_log: 'حفظ سجل الإنتاج',
    recent_logs: 'أحدث سجلات الإنتاج',
    shift_morning: 'وردية الصباح (٠٦:٠٠ - ١٤:٠٠)',
    shift_afternoon: 'وردية بعد الظهر (١٤:٠٠ - ٢٢:٠٠)',
    shift_night: 'وردية الليل (٢٢:٠٠ - ٠٦:٠٠)',
    log_submitted_success: 'تم تسجيل سجل الإنتاج وتحديث حركة المخزون بنجاح.',
    no_production_logs: 'لم يتم العثور على سجلات إنتاج.',
    time: 'الوقت',
    inventory_title: 'عمليات المخزون والمستودعات',
    intelligence_center: 'مركز التحليل',
    inventory_subtitle: 'مراقبة مستويات المخزون، الحركات الواردة والصادرة، وتقييم المستودع.',
    stock_operations: 'عمليات حركة المخزون',
    total_warehouse_value: 'إجمالي تقييم المستودع',
    storage_capacity: 'استغلال سعة التخزين',
    inventory_forecast: 'توقعات استنزاف المخزون',
    stock_movements: 'سجل حركات المخزون',
    stock_movements_subtitle: 'سجل تدقيق كامل لمعاملات المخزون الواردة والصادرة.',
    current_stock_label: 'المخزون الحالي',
    mutation_type: 'نوع الحركة',
    zone_utilization: 'استغلال مناطق المستودع',
    from_last_month: '+٢.٤٪ عن الشهر الماضي',
    capacity_sqft: 'قدم²',
    audit_passed: 'تم بنجاح',
    auditor_label: 'المدقق: ج. ميلر',
    no_stock_movements: 'لم يتم تسجيل أي حركات مخزون حتى الآن.',
    production_output: 'مخرجات الإنتاج',
    warehouse_dispatch: 'صرف من المستودع',
    zone_capacity_desc: 'سعة المستودع لكل قطاع تخزين (٪)',
    capacity_used: 'السعة المستخدمة',
    standard_storage: 'تخزين قياسي',
    hazmat_zone: 'منطقة المواد الخطرة',
    stock_out_note: 'ملاحظة: سيفشل الطلب إذا تجاوزت الكمية المطلوبة المخزون المتاح.',
    please_select_product: 'يرجى تحديد المنتج',
    export_inventory_success: 'تم تنزيل تقرير مخزون المصنع بنجاح.',
    reports_title: 'التقارير والتحليلات التنفيذية',
    reports_subtitle: 'رؤى تحليلية متعمقة لكفاءة التصنيع وسرعة المخزون وأداء المصنع.',
    monthly_yield: 'اتجاهات الإنتاجية والمخرجات الشهرية',
    monthly_yield_desc: 'إجمالي الإنتاج المجمع شهرياً في الوقت الفعلي من MSSQL',
    top_products_distribution: 'توزيع مخرجات أهم المنتجات',
    top_products_desc: 'التوزيع حسب حجم الإنتاج',
    machine_performance_heatmap: 'خريطة أداء أسطول الماكينات',
    heatmap_desc: 'وقت التشغيل والكفاءة عبر الوحدات النشطة (آخر ۲٤ ساعة)',
    heatmap_low: 'منخفض',
    heatmap_optimal: 'مثالي',
    forecast_desc: 'مستويات المخزون المتوقعة بناءً على معدل التشغيل الحالي',
    timeframe_last_30_days: 'آخر ٣٠ يوماً',
    timeframe_last_7_days: 'آخر ٧ أيام',
    timeframe_last_90_days: 'آخر ٩٠ يوماً',
    export_pdf: 'PDF',
    export_excel: 'EXCEL',
    export_csv: 'CSV',
    day_today: 'اليوم',
    day_prefix: 'يوم',
    users_title: 'إدارة المستخدمين والصلاحيات',
    access_control: 'التحكم بالوصول',
    users_subtitle: 'إدارة المشغلين والمشرفين وأذونات التحكم بالوصول المستندة إلى الأدوار (RBAC).',
    invite_user: 'إضافة مستخدم جديد',
    add_user_title: 'إضافة مستخدم جديد للنظام',
    add_user_desc: 'إنشاء بيانات اعتماد حساب المستخدم لقاعدة بيانات MSSQL',
    user_created_success: 'تم إنشاء حساب المستخدم بنجاح.',
    user_updated_success: 'تم تحديث دور المستخدم بنجاح.',
    user_deleted_success: 'تم حذف حساب المستخدم بنجاح.',
    manage_user: 'إدارة المستخدم',
    edit_user_role: 'تغيير الدور',
    delete_user: 'حذف المستخدم',
    confirm_delete_user: 'هل أنت متأكد أنك تريد حذف حساب المستخدم',
    no_users_found: 'لم يتم العثور على حسابات مستخدمين مطابقة للبحث.',
    loading_users: 'جاري تحميل حسابات المستخدمين...',
    all_roles: 'جميع الأدوار',
    admin_role: 'مسؤول النظام',
    admin_role_desc: 'وصول كامل للنظام وإدارة المستخدمين والتهيئة وإعدادات الأمان.',
    supervisor_role: 'مشرف',
    supervisor_role_desc: 'يمكنه مراجعة سجلات الإنتاج وإدارة الكتالوج وعرض التقارير التحليلية.',
    operator_role: 'مشغل',
    operator_role_desc: 'مصرح له بتسجيل الإنتاج اليومي وتدوين حركات المخزون.',
    role_permissions: 'تعريفات الأدوار والصلاحيات',
    active_status: 'نشط',
    last_audit: 'آخر نشاط',
    online: 'متصل',
    add_product_desc: 'تسجيل صنف مادة خام أو منتج نهائي جديد في الكتالوج الرئيسي.',
    category_electronics: 'الإلكترونيات والأتمتة',
    category_mechanical: 'القطع الميكانيكية',
    category_sensors: 'المستشعرات والمشغلات',
    category_raw: 'المواد الخام',
    category_plcs: 'وحدات التحكم PLC',
    unit_of_measure: 'وحدة القياس',
    unit_pcs: 'قطع (pcs)',
    unit_box: 'صناديق (box)',
    unit_meter: 'أمتار (m)',
    unit_kg: 'كيلوجرام (kg)',
    initial_stock_label: 'رصيد المخزون الافتتاحي',
    min_stock_label: 'حد المخزون الأدنى (مخزون الأمان)',
    primary_supplier_label: 'المورد / البائع الرئيسي',
    description: 'الوصف ومواصفات المنتج',
    import_csv: 'استيراد CSV',
    import_products_title: 'استيراد المنتجات من ملف CSV',
    import_products_desc: 'قم بتحميل ملف CSV لإدراج منتجات جديدة في الكتالوج الرئيسي دفعة واحدة.',
    download_template: 'تنزيل نموذج CSV',
    drag_drop_csv: 'انقر أو اسحب وأفلت ملف CSV هنا',
    valid_rows_found: 'الصفوف الصالحة الجاهزة للاستيراد',
    import_success: 'تم استيراد المنتجات بنجاح إلى الكتالوج الرئيسي.',
    export_catalog_csv: 'تصدير الكتالوج (CSV)',
    record_daily_production: 'تسجيل الإنتاج اليومي',
    record_daily_desc: 'تسجيل الوحدات المصنعة وتحديث مخزون المستودع فورياً.',
    select_product_prompt: 'حدد صنف المنتج',
    operator_name_label: 'المشغل المكلف',
    save_production_log: 'حفظ وزيادة المخزون',
    record_stock_out_title: 'تسجيل حركة خروج المخزون',
    record_stock_out_desc: 'خصم عناصر من مخزون المستودع للتوزيع أو استخدام خط الإنتاج.',
    quantity_deducted: 'الكمية المراد خصمها',
    confirm_stock_out: 'تأكيد خصم المخزون',
    confirm_sign_out: 'تأكيد تسجيل الخروج',
    sign_out_desc: 'هل أنت متأكد أنك تريد إنهاء جلسة محطة العمل هذه؟ سيتم فقد أي تعديلات غير محفوظة.',
    active_session: 'محطة العمل النشطة',
    yes_sign_out: 'نعم، تسجيل الخروج',
    signing_out: 'جارٍ تسجيل الخروج...',
    notification_center: 'مركز التنبيهات',
    notifications_desc: 'تنبيهات القياس المباشر وتحذيرات انخفاض المخزون وأحداث التشغيل.',
    mark_all_read: 'تعيين الكل كمقروء',
    all_filter: 'الكل',
    unread_filter: 'غير مقروء',
    critical_filter: 'حرج',
    clear_all: 'مسح الكل',
    confirm_clear_notifications: 'هل أنت متأكد من رغبتك في مسح جميع الإشعارات؟',
    no_notifications: 'لا توجد تنبيهات حالياً',
    new_badge: 'جديد',
    help_center_title: 'مركز المساعدة والتوثيق',
    documentation: 'التوثيق',
    help_center_subtitle: 'أدلة التشغيل وإجراءات العمل الموحدة (SOP) والدعم الفني.',
    quick_start_guide: 'دليل البدء السريع',
    quick_start_guide_desc: 'تعلم أساسيات لوحة التحكم والقياس عن بعد لمحطات العمل.',
    production_flow_guide: 'إجراءات تدفق وتسجيل الإنتاج',
    production_flow_guide_desc: 'الإجراءات الموحدة لتسجيل ورديات العمل واعتماد مخرجات المواد.',
    inventory_rules_guide: 'دليل المخزون وحدود الأمان',
    inventory_rules_guide_desc: 'كيفية عمل التنبيهات التلقائية عند انخفاض المخزون عن الحد الأدنى للأمان.',
    faq_title: 'الأسئلة الشائعة (FAQ)',
    faq_1_q: 'كيف يمكنني إضافة صنف منتج جديد إلى كتالوج المصنع؟',
    faq_1_a: 'انتقل إلى كتالوج المنتجات، انقر فوق "+ إضافة منتج"، املأ رمز الصنف وحد الأمان والمخزون الافتتاحي.',
    faq_2_q: 'ماذا يحدث عندما ينخفض المخزون عن الحد الأدنى؟',
    faq_2_a: 'يقوم النظام تلقائياً بتمييز العنصر باللون الأحمر في تنبيهات المخزون المنخفض وإرسال إشعار فوري.',
    faq_3_q: 'كيف يتم إعداد المصادقة الثنائية (2FA)؟',
    faq_3_a: 'انتقل إلى إعدادات النظام > الأمان وكلمة المرور، انقر فوق "تهيئة 2FA"، امسح رمز الاستجابة السريعة، وأدخل الرمز المكون من 6 أرقام.',
    contact_support: 'الاتصال بالدعم الفني',
    support_team_hours: 'مكتب دعم عمليات المصنع على مدار الساعة 24/7 • تحويلة 4040',
    open_support_ticket: 'إنشاء تذكرة دعم',
    back_to_dashboard: 'العودة إلى لوحة التحكم التنفيذية',
  },
  es: {
    // Navigation & Sidebar
    dashboard: 'Panel Ejecutivo',
    products: 'Catálogo de Productos',
    production_logs: 'Registros de Producción',
    inventory: 'Inventario y Stock',
    reports: 'Reportes y Analítica',
    users: 'Acceso y Roles de Usuario',
    settings: 'Configuración del Sistema',
    help: 'Centro de Ayuda',
    logout: 'Cerrar Sesión',
    main_menu: 'Navegación Principal',
    enterprise_automation: 'Automatización Empresarial',

    // Dashboard Page
    executive_dashboard: 'Panel Ejecutivo',
    smart_control: 'Automatización Inteligente',
    realtime_overview: 'Supervisión en tiempo real de operaciones de manufactura e inventario.',
    refresh: 'Sincronizar Datos en Vivo',
    sync_data: 'Sincronizar Datos',

    // Header & Quick Actions
    search_placeholder: 'Buscar operaciones, productos, registros...',
    export: 'Exportar Datos',
    new_action: 'Acción Rápida',
    add_new_product: '+ Agregar Nuevo Producto',
    record_production: 'Registrar Producción',
    record_stock_out: 'Registrar Salida de Stock',

    // KPI Summary Cards
    total_products: 'Total de Productos',
    today_production: 'Producción de Hoy',
    current_inventory: 'Nivel Actual de Stock',
    low_stock_alerts: 'Alertas de Stock Bajo',
    production_efficiency: 'Eficiencia de Línea (OEE)',
    active_catalog: 'Ítems activos en catálogo',
    vs_daily_target: 'vs meta diaria',
    total_items_in_stock: 'Total de ítems en stock',
    require_attention: 'Ítems que requieren atención',
    optimal_output: 'Rendimiento óptimo de línea',

    // Dashboard widgets
    recent_activity: 'Flujo de Producción en Vivo',
    stock_status: 'Niveles de Stock y Seguridad',
    quick_stats: 'Resumen Operativo',
    view_all_logs: 'Ver Registros de Auditoría',
    manage_inventory: 'Abrir Gestión de Inventario',

    // Stock levels
    in_stock: 'En Stock',
    low_stock: 'Stock Bajo',
    out_of_stock: 'Crítico',
    units_left: 'unidades restantes',

    // Forms and Modals
    add_product_title: 'Crear Producto en Catálogo',
    edit_product_title: 'Modificar Producto de Catálogo',
    product_name: 'Nombre del Producto',
    unit: 'Unidad de Medida',
    min_stock: 'Umbral de Stock de Seguridad',
    current_stock: 'Cantidad Actual de Stock',
    save_product: 'Guardar Producto',
    saving: 'Procesando...',
    confirm_delete: '¿Está seguro de que desea eliminar este registro?',
    confirm_delete_product: '¿Está seguro de que desea eliminar el producto',
    delete_product_success: 'Producto eliminado del catálogo principal con éxito.',
    delete_warning: 'Esta acción no se puede deshacer y eliminará los registros de telemetría asociados.',

    // Common
    success: 'Éxito',
    error: 'Error',
    warning: 'Advertencia',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver al Panel',
    sign_in: 'Iniciar Sesión en Centro de Control',
    username: 'Usuario / ID de Operador',
    password: 'Contraseña',
    login: 'Autenticar Sesión',
    logging_in: 'Autenticando...',
    login_subtitle: 'Ingrese sus credenciales para acceder a los sistemas de control industrial.',

    // Settings Module Full Localization
    system_settings: 'Configuración del Sistema',
    system_config: 'Configuración de Control Industrial',
    settings_description: 'Administre preferencias de plataforma, seguridad, reglas de notificación y conectividad industrial.',
    search_settings: 'Buscar configuraciones...',
    language: 'Idioma',
    select_language: 'Idioma de la Interfaz',
    language_subtitle: 'Seleccione su idioma preferido para el panel de control industrial.',
    preview_format: 'Vista Previa de Formato en Vivo',
    appearance: 'Apariencia Visual',
    appearance_subtitle: 'Personalice el contraste del tema, densidad de interfaz y estilo de telemetría.',
    theme: 'Modo de Tema',
    theme_dark: 'Forge Oscuro (Recomendado para Salas de Control)',
    theme_light: 'Clean Slate Claro',
    high_contrast: 'Modo de Alto Contraste',
    high_contrast_desc: 'Mejora la visibilidad en entornos de fábrica con iluminación brillante o reflejos.',
    ui_density: 'Densidad de Interfaz',
    density_comfortable: 'Cómoda (Táctil / Escritorio Estándar)',
    density_compact: 'Compacta (Telemetría de Alta Densidad)',
    accent_color: 'Color de Acento de Telemetría',
    accent_blue: 'Forge Blue',
    accent_emerald: 'Emerald Automation',
    accent_amber: 'Cyber Amber',
    accent_violet: 'Tech Violet',
    profile: 'Perfil de Usuario',
    profile_info: 'Perfil e Identidad del Operador',
    profile_subtitle: 'Administre su identidad de operador, información de contacto y terminal de fábrica.',
    full_name: 'Nombre Completo',
    department: 'Departamento / Unidad',
    job_title: 'Cargo / Puesto',
    phone_number: 'Teléfono de Contacto',
    timezone: 'Zona Horaria de Terminal',
    save_profile: 'Guardar Cambios de Perfil',
    profile_updated: 'Preferencias de perfil actualizadas con éxito.',
    security: 'Seguridad y Acceso',
    security_title: 'Seguridad y Autenticación',
    security_subtitle: 'Administre credenciales de acceso, verificación en dos pasos y terminales activas.',
    update_password: 'Actualizar Contraseña',
    current_password: 'Contraseña Actual',
    new_password: 'Nueva Contraseña',
    confirm_password: 'Confirmar Nueva Contraseña',
    password_updated: 'Contraseña actualizada con éxito.',
    two_factor_auth: 'Autenticación de Dos Factores (2FA)',
    two_factor_desc: 'Exija llave de seguridad o aplicación TOTP para acciones críticas en planta.',
    two_factor_status_active: '2FA Activo y Protegido',
    two_factor_status_inactive: '2FA Inactivo',
    two_factor_setup_btn: 'Configurar 2FA',
    two_factor_disable_btn: 'Desactivar 2FA',
    two_factor_modal_title: 'Configuración de Autenticación de Dos Factores (TOTP)',
    two_factor_step_1: '1. Escanee el código QR en la aplicación de autenticación',
    two_factor_step_1_desc: 'Escanee este código QR con Google Authenticator, Microsoft Authenticator o Apple Passwords.',
    two_factor_manual_key: 'Clave Secreta Manual',
    two_factor_copy_key: 'Copiar Clave',
    two_factor_copied: '¡Copiado!',
    two_factor_step_2: '2. Guarde los Códigos de Recuperación de Emergencia',
    two_factor_step_2_desc: 'Guarde estos 8 códigos de recuperación de un solo uso en un lugar seguro para iniciar sesión si pierde su dispositivo.',
    two_factor_step_3: '3. Verifique el Código TOTP de 6 Dígitos',
    two_factor_verify_btn: 'Verificar y Activar 2FA',
    two_factor_enabled_toast: '¡La autenticación de dos factores ya está activa!',
    two_factor_disabled_toast: 'La autenticación de dos factores ha sido desactivada.',
    two_factor_login_title: 'Autenticación de Dos Factores (2FA)',
    two_factor_login_prompt: 'Ingrese el código de verificación de 6 dígitos de su aplicación de autenticación o un código de recuperación.',
    two_factor_verify_login_btn: 'Verificar e Iniciar Sesión',
    active_sessions: 'Sesiones Activas en Planta',
    revoke_other_sessions: 'Cerrar Otras Sesiones',
    confirm_revoke_sessions: '¿Está seguro de que desea cerrar todas las demás sesiones de las estaciones de trabajo?',
    session_revoked: 'Todas las demás sesiones activas han sido cerradas con éxito.',
    notifications: 'Notificaciones',
    notification_rules: 'Reglas de Alerta y Notificación',
    notification_rules_desc: 'Configure activadores de alerta, umbrales de escalación y canales de entrega para eventos de planta.',
    delivery_channels: 'Canales de Entrega de Notificaciones',
    channel_in_app: 'Alertas en la Aplicación',
    channel_email: 'Resumen por Correo',
    channel_audio: 'Alerta Sonora de Sirena',
    alert_low_stock: 'Alertas de Seguridad por Stock Bajo',
    alert_low_stock_desc: 'Activar alerta cuando el inventario caiga por debajo del mínimo de seguridad.',
    alert_maintenance: 'Recordatorios de Mantenimiento de Máquinas (500h)',
    alert_maintenance_desc: 'Alertar a los operadores cuando las máquinas CNC o Prensa alcancen 500 horas.',
    alert_shift_batch: 'Resúmenes de Producción por Turno',
    alert_shift_batch_desc: 'Enviar resumen de producción por turno y registro de movimientos.',
    alert_db_sync: 'Advertencias de Sincronización y Latencia de BD',
    alert_db_sync_desc: 'Advertir ante picos de latencia en MSSQL o desconexiones de telemetría.',
    save_notifications: 'Guardar Reglas de Notificación',
    notifications_saved: 'Reglas de notificación guardadas con éxito.',
    help_faq: 'Centro de Ayuda y Preguntas Frecuentes',
    system: 'Operaciones de Fábrica',
    system_infra: 'Configuración Operativa e Infraestructura',
    system_infra_desc: 'Configure metas de producción por turno, estándares de eficiencia OEE, líneas de manufactura y respaldos de base de datos.',
    backend_api_url: 'URL del Gateway API Backend Go',
    mssql_db_host: 'Host y Catálogo de Base de Datos MSSQL',
    auto_sync_interval: 'Intervalo de Sondeo Automático',
    default_export_format: 'Formato Predeterminado de Exportación',
    telemetry_log_level: 'Nivel de Registro de Telemetría',
    trigger_backup: 'Ejecutar Respaldo Manual de Base de Datos',
    save_preferences: 'Guardar Configuración',
    system_config_saved: 'Configuración operativa de fábrica guardada con éxito.',
    shift_output_targets: 'Metas de Producción por Turno',
    target_shift_1: 'Meta Turno 1 (Mañana)',
    target_shift_2: 'Meta Turno 2 (Tarde)',
    target_shift_3: 'Meta Turno 3 (Noche)',
    oee_standard_target: 'Meta Estándar de Eficiencia OEE',
    global_safety_stock_threshold: 'Umbral Global de Stock de Seguridad',
    factory_production_lines: 'Líneas de Manufactura Activas',
    line_1_name: 'Línea 1 - Mecanizado y Fresado CNC',
    line_2_name: 'Línea 2 - Estampado y Prensa Hidráulica',
    line_3_name: 'Línea 3 - Ensamblaje Final y Empaque',
    backup_retention_policy: 'Respaldo y Política de Retención',
    auto_backup_schedule: 'Horario de Respaldo Automático',
    backup_shift_change: 'En Cada Cambio de Turno (8 Horas)',
    backup_daily_midnight: 'Diario a Medianoche (00:00)',
    backup_weekly_sunday: 'Semanal los Domingos',
    save_factory_config: 'Guardar Configuración Operativa',

    // Table headers & Details
    product_code: 'Código',
    category: 'Categoría',
    stock: 'Stock',
    min: 'Mín',
    shift: 'Turno',
    operator: 'Operador',
    machine_id: 'ID de Máquina',
    quantity: 'Cantidad',
    status: 'Estado',
    last_activity: 'Última Actividad',
    actions: 'Acciones',
    role: 'Rol',
    user: 'Usuario',
    last_login: 'Último Acceso',
    active_status_label: 'Activo',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operador',

    // Units & Measures
    units: 'unidades',
    pcs: 'pzas',
    produce: 'Producir',
    view_all: 'Ver Todo',
    showing: 'Mostrando',
    of: 'de',
    loading: 'Cargando...',

    // Timeframes & Days
    tf_7d: '7D',
    tf_30d: '30D',
    tf_ytd: 'YTD',
    days_mon: 'Lun',
    days_tue: 'Mar',
    days_wed: 'Mié',
    days_thu: 'Jue',
    days_fri: 'Vie',
    days_sat: 'Sáb',
    days_sun: 'Dom',

    // Buttons
    save: 'Guardar Producto',
    submit: 'Enviar',
    view: 'Ver',
    interface_language: 'Idioma de Interfaz',
    production_analytics: 'Análisis de Producción',
    production_analytics_subtitle: 'Telemetría en tiempo real y seguimiento de volumen de producción.',
    live_output: 'Salida en Vivo',
    quick_actions: 'Acciones Rápidas',
    quick_actions_subtitle: 'Control rápido de planta y movimientos de inventario.',
    add_product: 'Agregar Producto',
    stock_out_btn: 'Registrar Salida de Stock',
    system_status: 'Estado de la Infraestructura del Sistema',
    system_status_subtitle: 'Conectividad de base de datos MSSQL, latencia y estado de ejecución.',
    all_systems_nominal: 'Todos los Sistemas Operan Normal',
    last_sync_text: 'Sincronización automática de base de datos activa',
    synced: 'Sincronizado',
    low_stock_subtitle: 'SKUs críticos que requieren reabastecimiento inmediato.',
    action_required: 'Acción Requerida',
    out_of_stock_status: 'Sin Stock',
    low_stock_status: 'Stock Bajo',
    in_stock_status: 'En Stock',
    products_management: 'Gestión de Catálogo de Productos',
    master_catalog: 'Catálogo Principal',
    products_subtitle: 'Administre SKUs maestros de productos, umbrales mínimos de stock y listas de materiales.',
    search_products: 'Buscar productos por nombre o código...',
    all_statuses: 'Todos los Estados',
    product_id: 'ID de Producto',
    no_products: 'No se encontraron productos',
    production_logs_title: 'Registro y Ejecución de Producción',
    live_manufacturing_data: 'Datos de Planta en Vivo',
    production_logs_subtitle: 'Registre salidas de líneas de fabricación, turnos y aumentos automáticos de inventario.',
    new_log_entry: 'Nueva Entrada de Producción',
    select_product: 'Seleccionar Producto',
    operator_name: 'Nombre del Operador',
    select_machine: 'Seleccionar Máquina / Estación',
    quantity_produced: 'Cantidad Producida',
    mutation_date: 'Fecha y Hora de Producción',
    submit_log: 'Guardar Registro de Producción',
    recent_logs: 'Registros Recientes de Producción',
    shift_morning: 'Turno Mañana (06:00 - 14:00)',
    shift_afternoon: 'Turno Tarde (14:00 - 22:00)',
    shift_night: 'Turno Noche (22:00 - 06:00)',
    log_submitted_success: 'Registro de producción guardado y stock actualizado con éxito.',
    no_production_logs: 'No se encontraron registros de producción.',
    time: 'Hora',
    inventory_title: 'Operaciones de Inventario y Almacén',
    intelligence_center: 'Centro de Inteligencia',
    inventory_subtitle: 'Monitoree niveles de inventario, movimientos de entrada/salida y valoración de almacén.',
    stock_operations: 'Operaciones de Stock',
    total_warehouse_value: 'Valoración Total del Almacén',
    storage_capacity: 'Utilización de Capacidad de Almacenamiento',
    inventory_forecast: 'Pronóstico de Agotamiento de Stock',
    stock_movements: 'Libro Mayor de Movimientos de Stock',
    stock_movements_subtitle: 'Pista de auditoría completa de transacciones de stock ENTRADA y SALIDA.',
    current_stock_label: 'Stock Actual',
    mutation_type: 'Tipo de Movimiento',
    zone_utilization: 'Utilización de Zonas del Almacén',
    from_last_month: '+2.4% respecto al mes anterior',
    capacity_sqft: 'pies²',
    audit_passed: 'APROBADO',
    auditor_label: 'Auditor: J. Miller',
    no_stock_movements: 'No hay movimientos de stock registrados aún.',
    production_output: 'Producción de Planta',
    warehouse_dispatch: 'Despacho de Almacén',
    zone_capacity_desc: 'Capacidad de almacén por sector de almacenamiento (%)',
    capacity_used: 'Capacidad Utilizada',
    standard_storage: 'Almacenamiento Estándar',
    hazmat_zone: 'Zona de Materiales Peligrosos',
    stock_out_note: 'Nota: La solicitud fallará si la cantidad excede el stock disponible.',
    please_select_product: 'Por favor seleccione un producto',
    export_inventory_success: 'Informe de inventario de fábrica descargado con éxito.',
    reports_title: 'Informes y Análisis Ejecutivo',
    reports_subtitle: 'Análisis profundo de la eficiencia de fabricación, rotación de stock y rendimiento de planta.',
    monthly_yield: 'Tendencias de Rendimiento y Producción Mensual',
    monthly_yield_desc: 'Producción agregada mensual en tiempo real desde MSSQL',
    top_products_distribution: 'Distribución de Producción de Productos Principales',
    top_products_desc: 'Distribución por volumen de producción',
    machine_performance_heatmap: 'Mapa de Rendimiento de la Flota de Máquinas',
    heatmap_desc: 'Tiempo de actividad y eficiencia en unidades activas (Últimas 24h)',
    heatmap_low: 'Bajo',
    heatmap_optimal: 'Óptimo',
    forecast_desc: 'Niveles de stock proyectados según el ritmo actual',
    timeframe_last_30_days: 'Últimos 30 Días',
    timeframe_last_7_days: 'Últimos 7 Días',
    timeframe_last_90_days: 'Últimos 90 Días',
    export_pdf: 'PDF',
    export_excel: 'EXCEL',
    export_csv: 'CSV',
    day_today: 'Hoy',
    day_prefix: 'Día',
    users_title: 'Gestión de Usuarios y Roles',
    access_control: 'Control de Acceso',
    users_subtitle: 'Administre permisos RBAC de operadores, supervisores y administradores.',
    invite_user: 'Agregar Nuevo Usuario',
    add_user_title: 'Agregar Nuevo Usuario de Plataforma',
    add_user_desc: 'Crear credenciales de cuenta de usuario para base de datos MSSQL',
    user_created_success: 'Cuenta de usuario creada con éxito.',
    user_updated_success: 'Rol de usuario actualizado con éxito.',
    user_deleted_success: 'Cuenta de usuario eliminada con éxito.',
    manage_user: 'Administrar Usuario',
    edit_user_role: 'Cambiar Rol',
    delete_user: 'Eliminar Usuario',
    confirm_delete_user: '¿Está seguro de que desea eliminar la cuenta de usuario',
    no_users_found: 'No se encontraron cuentas de usuario que coincidan.',
    loading_users: 'Cargando cuentas de usuario...',
    all_roles: 'Todos los Roles',
    admin_role: 'Administrador',
    admin_role_desc: 'Acceso completo al sistema, gestión de usuarios, configuración y seguridad.',
    supervisor_role: 'Supervisor',
    supervisor_role_desc: 'Puede supervisar registros de producción, gestionar el catálogo y ver informes analíticos.',
    operator_role: 'Operador',
    operator_role_desc: 'Autorizado para el registro diario de producción y movimientos de stock.',
    role_permissions: 'Definiciones de Roles y Permisos',
    active_status: 'Activo',
    last_audit: 'Última Actividad',
    online: 'En Línea',
    add_product_desc: 'Registre un nuevo SKU de materia prima o producto terminado en el catálogo.',
    category_electronics: 'Electrónica y Automatización',
    category_mechanical: 'Piezas Mecánicas',
    category_sensors: 'Sensores y Actuadores',
    category_raw: 'Materias Primas',
    category_plcs: 'PLCs y Controladores',
    unit_of_measure: 'Unidad de Medida',
    unit_pcs: 'Piezas (pcs)',
    unit_box: 'Cajas (box)',
    unit_meter: 'Metros (m)',
    unit_kg: 'Kilogramos (kg)',
    initial_stock_label: 'Stock Inicial de Apertura',
    min_stock_label: 'Umbral Mínimo de Stock (Stock de Seguridad)',
    primary_supplier_label: 'Proveedor / Vendedor Principal',
    description: 'Descripción y Especificaciones del Producto',
    import_csv: 'Importar CSV',
    import_products_title: 'Importar Productos desde CSV',
    import_products_desc: 'Cargue un archivo CSV para insertar nuevos productos en el catálogo principal por lotes.',
    download_template: 'Descargar Plantilla CSV',
    drag_drop_csv: 'Haga clic o arrastre el archivo CSV aquí',
    valid_rows_found: 'Filas válidas listas para importar',
    import_success: 'Productos importados con éxito al catálogo principal.',
    export_catalog_csv: 'Exportar Catálogo (CSV)',
    record_daily_production: 'Registrar Producción Diaria',
    record_daily_desc: 'Registre unidades fabricadas y actualice el stock del almacén al instante.',
    select_product_prompt: 'Seleccionar SKU de Producto',
    operator_name_label: 'Operador Asignado',
    save_production_log: 'Guardar e Incrementar Stock',
    record_stock_out_title: 'Registrar Salida de Stock',
    record_stock_out_desc: 'Deducir artículos del inventario para distribución o uso en producción.',
    quantity_deducted: 'Cantidad a Deducir',
    confirm_stock_out: 'Confirmar Deducción de Stock',
    confirm_sign_out: 'Confirmar Cierre de Sesión',
    sign_out_desc: '¿Está seguro de que desea cerrar la sesión de su estación de trabajo? Los cambios no guardados se descartarán.',
    active_session: 'Estación Activa',
    yes_sign_out: 'Sí, Cerrar Sesión',
    signing_out: 'Cerrando sesión...',
    notification_center: 'Centro de Notificaciones',
    notifications_desc: 'Alertas de telemetría en tiempo real, advertencias de stock bajo y eventos operativos.',
    mark_all_read: 'Marcar Todo como Leído',
    all_filter: 'Todos',
    unread_filter: 'No Leídos',
    critical_filter: 'Críticos',
    clear_all: 'Limpiar Todo',
    confirm_clear_notifications: '¿Está seguro de que desea borrar todas las notificaciones?',
    no_notifications: 'No hay notificaciones para mostrar',
    new_badge: 'NUEVO',
    help_center_title: 'Centro de Ayuda y Documentación',
    documentation: 'Documentación',
    help_center_subtitle: 'Guías operativas, procedimientos estándar (SOP) y soporte técnico.',
    quick_start_guide: 'Guía de Inicio Rápido',
    quick_start_guide_desc: 'Aprenda los fundamentos del panel y la telemetría de estaciones de trabajo.',
    production_flow_guide: 'SOP de Flujo y Registro de Producción',
    production_flow_guide_desc: 'Procedimientos estándar para registrar turnos y validar salidas de material.',
    inventory_rules_guide: 'Guía de Inventario y Umbrales de Seguridad',
    inventory_rules_guide_desc: 'Cómo funcionan las alertas automáticas cuando el stock cae por debajo del mínimo.',
    faq_title: 'Preguntas Frecuentes (FAQ)',
    faq_1_q: '¿Cómo agrego un nuevo SKU de producto al catálogo de la planta?',
    faq_1_a: 'Vaya a Catálogo de Productos, haga clic en "+ Agregar Producto", ingrese el código, el umbral de seguridad y el stock inicial.',
    faq_2_q: '¿Qué sucede cuando el stock cae por debajo del umbral mínimo?',
    faq_2_a: 'El sistema marca automáticamente el artículo en rojo en Alertas de Stock Bajo y envía una notificación instantánea.',
    faq_3_q: '¿Cómo se configura la Autenticación de Dos Factores (2FA)?',
    faq_3_a: 'Vaya a Configuración del Sistema > Seguridad y Contraseña, haga clic en "Configurar 2FA", escanee el código QR e ingrese el código de 6 dígitos.',
    contact_support: 'Contactar al Soporte Técnico',
    support_team_hours: 'Soporte de Operaciones de Planta 24/7 • Extensión 4040',
    open_support_ticket: 'Crear Ticket de Soporte',
    back_to_dashboard: 'Volver al Panel Ejecutivo',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const subscribeLang = (callback: () => void) => {
  window.addEventListener('storage', callback)
  window.addEventListener('forge_lang_change', callback)
  return () => {
    window.removeEventListener('storage', callback)
    window.removeEventListener('forge_lang_change', callback)
  }
}

const getLangSnapshot = (): Language => {
  try {
    const saved = localStorage.getItem('forge_lang') as Language
    if (saved && ['en', 'id', 'ar', 'es'].includes(saved)) return saved
  } catch {}
  return 'en'
}

const getServerLangSnapshot = (): Language => 'en'

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const language = useSyncExternalStore(
    subscribeLang,
    getLangSnapshot,
    getServerLangSnapshot
  )

  const setLanguage = (lang: Language) => {
    try {
      localStorage.setItem('forge_lang', lang)
      window.dispatchEvent(new Event('forge_lang_change'))
    } catch {}
  }

  const isRTL = language === 'ar'

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  const formatNumber = (value: number | string | null | undefined): string => {
    return formatNumberByLang(value, language)
  }

  const formatDate = (date?: Date | string | number, options?: Intl.DateTimeFormatOptions): string => {
    return formatDateByLang(date, language, options)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, formatNumber, formatDate, isRTL }}>
      <div
        dir="ltr"
        className={language === 'ar' ? 'font-arabic' : ''}
        style={{ minHeight: '100%' }}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
