'use client'

import React, { createContext, useContext, useState, useSyncExternalStore } from 'react'

export type Language = 'en' | 'id' | 'ar' | 'es'

export interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  formatNumber: (value: number | string | null | undefined) => string
  formatDate: (date?: Date | string | number, options?: Intl.DateTimeFormatOptions) => string
  isRTL: boolean
}

export function formatNumberByLang(
  value: number | string | null | undefined,
  lang: Language = 'en'
): string {
  if (value === null || value === undefined) return ''
  const str = String(value)
  if (lang === 'ar') {
    const arabicDigits = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩']
    return str
      .replace(/[0-9]/g, (d) => arabicDigits[Number(d)])
      .replace(/,/g, '،')
      .replace(/%/g, '٪')
  }
  return str
}

export function formatDateByLang(
  date: Date | string | number = new Date(),
  lang: Language = 'en',
  options?: Intl.DateTimeFormatOptions
): string {
  const d = typeof date === 'string' || typeof date === 'number' ? new Date(date) : date
  const localeMap: Record<Language, string> = {
    en: 'en-US',
    id: 'id-ID',
    ar: 'ar-EG',
    es: 'es-ES'
  }
  const defaultOptions: Intl.DateTimeFormatOptions = options || {
    weekday: 'short',
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  }
  try {
    const formatted = new Intl.DateTimeFormat(localeMap[lang] || 'en-US', defaultOptions).format(d)
    return formatNumberByLang(formatted, lang)
  } catch {
    return d.toDateString()
  }
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Sidebar
    dashboard: 'Executive Dashboard',
    products: 'Product Catalog',
    production_logs: 'Production Logs',
    inventory: 'Inventory & Stock',
    reports: 'Reports & Analytics',
    users: 'User Access & Roles',
    settings: 'System Settings',
    help: 'Help Center',
    logout: 'Sign Out',
    main_menu: 'Main Navigation',
    enterprise_automation: 'Enterprise Automation',

    // Dashboard Page
    executive_dashboard: 'Executive Dashboard',
    smart_control: 'Smart Automation',
    realtime_overview: 'Real-time overview of global manufacturing operations & inventory.',
    refresh: 'Sync Live Data',
    sync_data: 'Sync Data',

    // Header & Quick Actions
    search_placeholder: 'Search operations, products, logs...',
    export: 'Export Data',
    new_action: 'Quick Action',
    add_new_product: '+ Add New Product',
    record_production: 'Record Production',
    record_stock_out: 'Record Stock Out',

    // KPI Summary Cards
    total_products: 'Total Products',
    today_production: "Today's Production",
    current_inventory: 'Current Stock Level',
    low_stock_alerts: 'Low Stock Alerts',
    production_efficiency: 'Line Efficiency (OEE)',
    active_catalog: 'Active catalog items',
    vs_daily_target: 'vs daily target',
    total_items_in_stock: 'Total items in stock',
    require_attention: 'Items require attention',
    optimal_output: 'Optimal line output',

    // Dashboard widgets
    quick_actions: 'Quick Operations',
    quick_actions_subtitle: 'Direct manufacturing inputs & inventory transactions',
    system_status: 'Infrastructure Status',
    system_status_subtitle: 'Live database and backend API health monitoring',
    all_systems_nominal: 'All Systems Nominal',
    last_sync_text: 'Last sync: 2 mins ago (Port 6060/6063)',
    online: 'Online',
    synced: 'Synced',
    action_required: 'Action Required',
    low_stock_subtitle: 'Products falling below minimum safety threshold',
    live_output: 'Live Output',
    production_analytics: 'Production Analytics',
    production_analytics_subtitle: 'Real-time daily manufacturing output & yield efficiency trend',

    // Products Module & Modal
    products_management: 'Product Catalog & Specifications',
    master_catalog: 'Master Catalog',
    products_subtitle: 'Manage manufacturing specifications, bill of materials, and safety thresholds.',
    search_products: 'Search products by name or ID...',
    add_product: 'Add Product',
    add_product_title: 'Add New Product',
    add_product_desc: 'Enter product details for inventory tracking.',
    product_name: 'Product Name',
    category: 'Category',
    unit_of_measure: 'Unit of Measure',
    initial_stock: 'Initial Stock',
    initial_stock_label: 'Initial Stock',
    min_stock_level: 'Min. Stock Level',
    min_stock_label: 'Min. Stock Level',
    primary_supplier: 'Primary Supplier',
    primary_supplier_label: 'Primary Supplier',
    description: 'Description',
    active_status: 'Active Status',
    all_categories: 'All Categories',
    all_statuses: 'All Statuses',
    in_stock_status: 'In Stock',
    low_stock_status: 'Low Stock',
    out_of_stock_status: 'Out of Stock',
    product_id: 'Product ID',
    unit: 'Unit',
    current_stock: 'Current Stock',
    min_stock: 'Min Stock',
    save_product: 'Save Product',
    category_electronics: 'Electronics & Automation',
    category_mechanical: 'Mechanical Parts',
    category_sensors: 'Sensors & Transducers',
    category_plcs: 'PLCs & Controllers',
    category_raw: 'Raw Materials',
    unit_pcs: 'Pieces (pcs)',
    unit_box: 'Boxes (box)',
    unit_meter: 'Meters (m)',
    unit_kg: 'Kilograms (kg)',

    // Production Logs Module & Modal
    production_logs_title: 'Manufacturing Production Logs',
    live_manufacturing_data: 'Live Factory Output',
    production_logs_subtitle: 'Record shift output, track machine operations, and monitor batch quantities.',
    new_log_entry: 'New Production Log Entry',
    recent_logs: 'Recent Production History',
    record_daily_production: 'Record Daily Production',
    record_daily_desc: 'Log output quantity & automatically mutate stock IN',
    select_product: 'Target Product',
    select_product_prompt: 'Select Target Product *',
    select_machine: 'Assigned Machine',
    assigned_machine: 'Machine / Workstation',
    quantity_produced: 'Produced Quantity',
    output_quantity: 'Output Quantity',
    shift: 'Work Shift',
    operator_name: 'Operator In Charge',
    operator_name_label: 'Operator Name',
    submit_log: 'Submit Production Log',
    save_production_log: 'Submit Production Log',
    log_id: 'Log ID',
    timestamp: 'Timestamp',
    filter_by_machine: 'All Machines',

    // Inventory Module & Modal
    inventory_title: 'Inventory & Warehouse Operations',
    stock_operations: 'Stock Operations',
    inventory_subtitle: 'Audit movements, monitor storage capacity, and track material valuations.',
    inventory_management: 'Inventory Management',
    stock_movements: 'Stock Movements Audit',
    stock_movements_subtitle: 'Comprehensive audit trail of incoming (IN) and outgoing (OUT) inventory mutations.',
    total_warehouse_value: 'Total Warehouse Valuation',
    storage_capacity: 'Warehouse Storage Capacity',
    last_audit: 'Last Inventory Audit',
    zone_utilization: 'Storage Zone Utilization',
    all_movements: 'All Movements',
    incoming_in: 'Stock In (Production)',
    outgoing_out: 'Stock Out (Dispatch)',
    movement_id: 'Movement ID',
    mutation_type: 'Mutation Type',
    mutation_date: 'Date & Time',
    export_report: 'Export Report',
    stock_out_btn: 'Dispatch Stock (Out)',
    record_stock_out_title: 'Record Inventory Stock Out',
    record_stock_out_desc: 'Deduct stock for distribution or maintenance',
    quantity_deducted: 'Quantity Deducted',
    confirm_stock_out: 'Confirm Stock Out',

    // Reports Module
    reports_title: 'Operational Analytics & Reports',
    intelligence_center: 'Intelligence Hub',
    reports_subtitle: 'In-depth yield metrics, machine performance breakdown, and inventory forecasts.',
    reports_analytics: 'Reports & Analytics',
    monthly_yield: 'Monthly Production Yield Trend',
    top_products_distribution: 'Top Products Volume Share',
    machine_performance_heatmap: 'Machine Operational Heatmap',
    inventory_forecast: '30-Day Inventory Stock Forecast',

    // Users Module
    users_title: 'User Access & Role Management',
    access_control: 'Access Control & Security',
    users_subtitle: 'Manage user credentials, assign role tiers, and configure platform authorizations.',
    user_management: 'User Management',
    registered_users: 'Registered Platform Users',
    invite_user: 'Create User Account',
    role_permissions: 'Role Permissions Matrix',
    all_roles: 'All Roles',
    admin_role: 'Administrator',
    manager_role: 'Manager',
    supervisor_role: 'Supervisor',
    operator_role: 'Operator',
    admin_role_desc: 'Full system privileges. Manages configurations, billing, audits, and user accounts.',
    supervisor_role_desc: 'Supervises production lines, generates analytics reports, and approves schedules.',
    operator_role_desc: 'Executes work orders, logs daily machine batches, and views line output.',
    manage_roles: 'Manage platform access, roles, and security permissions.',

    // Settings Module (All 6 Tabs)
    system_settings: 'System Settings & Preferences',
    system_config: 'System Config',
    settings_description: 'Manage account configuration, language localization, and system preferences.',
    search_settings: 'Search settings...',
    select_language: 'Select Interface Language',
    language: 'Language',
    language_subtitle: 'Choose your preferred control center language.',
    appearance: 'Appearance',
    appearance_subtitle: 'Customize visual theme, contrast, and layout density.',
    theme: 'Theme Mode',
    theme_dark: 'Dark Mode',
    theme_light: 'Light Mode',
    high_contrast: 'High Contrast Mode',
    high_contrast_desc: 'Increase contrast for better readability in harsh lighting.',
    ui_density: 'Interface Density',
    density_comfortable: 'Comfortable (Standard)',
    density_compact: 'Compact (Industrial High-Density)',
    accent_color: 'Accent Color Palette',
    accent_blue: 'Forge Blue',
    accent_emerald: 'Emerald Automation',
    accent_amber: 'Cyber Amber',
    accent_violet: 'Tech Violet',
    preview_format: 'Format & Number Preview',

    profile: 'Profile',
    profile_info: 'User Profile & Identity',
    profile_subtitle: 'Manage your operator credentials, department, and contact information.',
    full_name: 'Full Name',
    job_title: 'Job Title',
    department: 'Department',
    phone_number: 'Contact Phone',
    timezone: 'System Timezone',
    save_profile: 'Save Profile',
    profile_updated: 'Profile credentials updated successfully.',

    security: 'Security',
    security_title: 'Security & Authentication',
    security_subtitle: 'Manage security keys, two-factor authentication, and active workstation sessions.',
    current_password: 'Current Password / Key',
    new_password: 'New Security Key',
    confirm_password: 'Confirm New Security Key',
    update_password: 'Change Password',
    two_factor_auth: 'Two-Factor Authentication (2FA)',
    two_factor_desc: 'Enforce hardware token or authenticator app code on login.',
    active_sessions: 'Active Workstation Sessions',
    revoke_other_sessions: 'Terminate Other Sessions',
    session_revoked: 'All other remote sessions have been terminated.',
    password_updated: 'Security key changed successfully.',

    notifications: 'Notifications',
    notification_rules: 'Notification Rules & Alert Channels',
    notification_rules_desc: 'Configure alert triggers for automated factory telemetry.',
    channel_in_app: 'In-App Alerts',
    channel_email: 'Email Digest',
    channel_audio: 'Audible Siren Alert',
    alert_low_stock: 'Low Stock Safety Threshold Alert',
    alert_maintenance: 'Machine Preventive Maintenance Alert',
    alert_shift_batch: 'Shift Batch Production Output Reports',
    alert_db_sync: 'Database & Telemetry Synchronization Warnings',
    save_notifications: 'Save Notification Rules',
    notifications_saved: 'Notification rules saved successfully.',

    system: 'System',
    system_infra: 'Core Infrastructure & Engine',
    system_infra_desc: 'Live backend runtime endpoints, database topology, and telemetry polling.',
    backend_api_url: 'Go Backend Endpoint',
    mssql_db_host: 'MSSQL 2022 Cluster',
    auto_sync_interval: 'Telemetry Auto-Sync Polling Interval',
    default_export_format: 'Default Data Export Format',
    telemetry_log_level: 'Telemetry Logging Level',
    trigger_backup: 'Trigger Manual Database Backup',
    backup_initiated: 'Database snapshot initiated on Port 6063.',
    system_config_saved: 'Infrastructure configuration updated.',

    configuration: 'Configuration',
    config_active: 'Configuration options for',
    config_active_suffix: 'are active.',
    system_roles: 'System Roles',
    manage_user_access: 'Manage user access and permissions.',
    add_user: 'Add User',
    save_preferences: 'Save Preferences',

    // Help Center Module & FAQs
    help_center_title: 'Help & Knowledge Center',
    help_center_subtitle: 'System guides, operational standard procedures, and technical documentation.',
    back_to_dashboard: 'Back to Executive Dashboard',
    faq_title: 'Frequently Asked Questions',
    documentation: 'Documentation',
    contact_support: 'Technical Support',
    support_team_hours: 'Engineering team on standby (24/7 Monitoring)',
    open_support_ticket: 'Open Support Ticket',
    quick_start_guide: 'System Architecture & Ports',
    quick_start_guide_desc: 'Overview of Go Backend (Port 6060), Next.js Frontend (Port 6061), and MSSQL 2022 (Port 6063).',
    production_flow_guide: 'Production Logging Flow',
    production_flow_guide_desc: 'How production logs automatically trigger stock mutations (Movement IN) with ACID transactions.',
    inventory_rules_guide: 'Inventory Safety Thresholds',
    inventory_rules_guide_desc: 'Color-coded visual warnings: Emerald (Normal), Amber (Low Stock), and Crimson (Out of Stock).',
    faq_1_q: 'How do I record finished manufacturing items?',
    faq_1_a: 'Use the Quick Action "+ Record Production" button on the dashboard or navigate to Production Logs module.',
    faq_2_q: 'How does automatic stock replenishment work?',
    faq_2_a: 'Whenever a production log is submitted, the Go backend executes a database transaction that creates an IN inventory movement and updates the current stock.',
    faq_3_q: 'Can I switch language and theme at any time?',
    faq_3_a: 'Yes, use the global Language selector in the top navigation bar or go to System Settings.',

    // Notifications Modal
    notification_center: 'Notification Center',
    notifications_desc: 'Real-time operational alerts, inventory warnings, and system logs.',
    mark_all_read: 'Mark all as read',
    clear_all: 'Clear all',
    new_badge: 'new',
    all_filter: 'All',
    unread_filter: 'Unread',
    critical_filter: 'Critical',
    no_notifications: 'No notifications found',
    produce_stock_btn: 'Produce Stock',
    schedule_btn: 'Schedule',
    notif_1_title: 'Low Stock Alert Breached',
    notif_1_msg: 'Servo Motor A-12 is currently at 2 units (Minimum threshold: 10 units). Immediate restocking recommended.',
    notif_2_title: 'Scheduled Maintenance Warning',
    notif_2_msg: 'Machine CNC-01 (Milling) has reached 500 operating hours. Maintenance check due in 4 hours.',
    notif_3_title: 'Production Shift Batch Completed',
    notif_3_msg: 'Shift A completed 45 units of Titanium Casing Alpha by operator J. Miller. Inventory mutated +45 pcs.',
    notif_4_title: 'MSSQL Database Sync Successful',
    notif_4_msg: 'Automated backup & telemetry index synchronization completed successfully on port 6063.',

    // Logout Modal
    confirm_sign_out: 'Confirm Sign Out',
    sign_out_desc: 'Are you sure you want to end your session? You will need to sign in again to access the control center.',
    active_session: 'Active Session',
    yes_sign_out: 'Yes, Sign Out',
    signing_out: 'Signing Out...',

    // Relative Time & Status
    '2_mins_ago': '2 mins ago',
    '5_mins_ago': '5 mins ago',
    '25_mins_ago': '25 mins ago',
    '1_hour_ago': '1 hour ago',
    '3_hours_ago': '3 hours ago',
    yesterday: 'Yesterday',
    offline_status_label: 'Offline',

    // Table Headers & Labels
    time: 'Time',
    operator: 'Operator',
    machine_id: 'Machine ID',
    quantity: 'Quantity',
    status: 'Status',
    last_activity: 'Last Activity',
    actions: 'Actions',
    role: 'Role',
    user: 'User',
    last_login: 'Last Login',
    active_status_label: 'Active',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operator',

    // Units & Measures
    units: 'units',
    pcs: 'pcs',
    produce: 'Produce',
    view_all: 'View All',
    showing: 'Showing',
    of: 'of',
    loading: 'Loading...',

    // Timeframes & Days
    tf_7d: '7D',
    tf_30d: '30D',
    tf_ytd: 'YTD',
    days_mon: 'Mon',
    days_tue: 'Tue',
    days_wed: 'Wed',
    days_thu: 'Thu',
    days_fri: 'Fri',
    days_sat: 'Sat',
    days_sun: 'Sun',

    // Buttons
    save: 'Save Product',
    cancel: 'Cancel',
    submit: 'Submit',
    view: 'View',
    edit: 'Edit',
    delete: 'Delete',
    interface_language: 'Interface Language',
  },

  id: {
    // Navigation & Sidebar
    dashboard: 'Dashboard',
    products: 'Master Produk',
    production_logs: 'Log Produksi',
    inventory: 'Manajemen Stok',
    reports: 'Laporan & Analitik',
    users: 'Manajemen Pengguna',
    settings: 'Pengaturan Sistem',
    help: 'Pusat Bantuan',
    logout: 'Keluar Akun',
    main_menu: 'Menu Utama',
    enterprise_automation: 'Otomasi Industri Terpadu',

    // Dashboard Page
    executive_dashboard: 'Dashboard Eksekutif',
    smart_control: 'Otomasi Cerdas',
    realtime_overview: 'Gambaran terpadu operasional manufaktur & pemantauan inventaris real-time.',
    refresh: 'Sinkronisasi Data',
    sync_data: 'Sinkron Data',

    // Header & Quick Actions
    search_placeholder: 'Cari operasional, produk, riwayat log...',
    export: 'Ekspor Data',
    new_action: 'Aksi Cepat',
    add_new_product: '+ Tambah Produk Baru',
    record_production: 'Catat Produksi Harian',
    record_stock_out: 'Catat Pengeluaran Stok',

    // KPI Summary Cards
    total_products: 'Total Produk Aktif',
    today_production: 'Produksi Hari Ini',
    current_inventory: 'Total Stok Gudang',
    low_stock_alerts: 'Peringatan Stok Rendah',
    production_efficiency: 'Efisiensi Lini (OEE)',
    active_catalog: 'Item katalog aktif',
    vs_daily_target: 'vs target harian',
    total_items_in_stock: 'Total item di gudang',
    require_attention: 'Item butuh perhatian',
    optimal_output: 'Output lini optimal',

    // Dashboard widgets
    quick_actions: 'Aksi Cepat Operasional',
    quick_actions_subtitle: 'Input manufaktur langsung & transaksi pergerakan stok',
    system_status: 'Status Infrastruktur',
    system_status_subtitle: 'Pemantauan real-time basis data dan API backend',
    all_systems_nominal: 'Semua Sistem Beroperasi Normal',
    last_sync_text: 'Sinkronisasi terakhir: 2 mnt lalu (Port 6060/6063)',
    online: 'Online',
    synced: 'Tersinkron',
    action_required: 'Perlu Tindakan Segera',
    low_stock_subtitle: 'Daftar produk di bawah batas aman minimum',
    live_output: 'Output Langsung',
    production_analytics: 'Analitik Produksi',
    production_analytics_subtitle: 'Tren harian hasil manufaktur dan efisiensi lini secara real-time',

    // Products Module & Modal
    products_management: 'Katalog Produk & Spesifikasi',
    master_catalog: 'Katalog Master',
    products_subtitle: 'Kelola spesifikasi manufaktur, bill of materials, dan batas stok aman.',
    search_products: 'Cari produk berdasarkan nama atau kode...',
    add_product: 'Tambah Produk',
    add_product_title: 'Tambah Produk Baru',
    add_product_desc: 'Masukkan detail produk untuk pelacakan inventaris pabrik.',
    product_name: 'Nama Produk',
    category: 'Kategori',
    unit_of_measure: 'Satuan Ukuran',
    initial_stock: 'Stok Awal',
    initial_stock_label: 'Stok Awal',
    min_stock_level: 'Batas Stok Minimum',
    min_stock_label: 'Batas Stok Minimum',
    primary_supplier: 'Pemasok Utama',
    primary_supplier_label: 'Pemasok Utama',
    description: 'Deskripsi',
    active_status: 'Status Aktif',
    all_categories: 'Semua Kategori',
    all_statuses: 'Semua Status',
    in_stock_status: 'Stok Aman',
    low_stock_status: 'Stok Rendah',
    out_of_stock_status: 'Stok Habis',
    product_id: 'Kode Produk',
    unit: 'Satuan',
    current_stock: 'Stok Saat Ini',
    min_stock: 'Min Stok',
    save_product: 'Simpan Produk',
    category_electronics: 'Elektronik & Otomasi',
    category_mechanical: 'Komponen Mekanikal',
    category_sensors: 'Sensor & Transduser',
    category_plcs: 'PLC & Kontroler',
    category_raw: 'Bahan Baku',
    unit_pcs: 'Pcs (Buah)',
    unit_box: 'Kotak (box)',
    unit_meter: 'Meter (m)',
    unit_kg: 'Kilogram (kg)',

    // Production Logs Module & Modal
    production_logs_title: 'Log Produksi Manufaktur',
    live_manufacturing_data: 'Hasil Pabrik Langsung',
    production_logs_subtitle: 'Catat output per shift, pantau kerja mesin, dan rekam kuantitas batch.',
    new_log_entry: 'Input Log Produksi Baru',
    recent_logs: 'Riwayat Log Produksi Terbaru',
    record_daily_production: 'Catat Produksi Harian',
    record_daily_desc: 'Catat kuantitas output & mutasikan stok MASUK secara otomatis',
    select_product: 'Produk Sasaran',
    select_product_prompt: 'Pilih Produk Sasaran *',
    select_machine: 'Mesin Produksi',
    assigned_machine: 'Mesin / Stasiun Kerja',
    quantity_produced: 'Jumlah Diproduksi',
    output_quantity: 'Jumlah Output',
    shift: 'Shift Kerja',
    operator_name: 'Operator Bertugas',
    operator_name_label: 'Nama Operator',
    submit_log: 'Simpan Log Produksi',
    save_production_log: 'Simpan Log Produksi',
    log_id: 'Kode Log',
    timestamp: 'Waktu Catat',
    filter_by_machine: 'Semua Mesin',

    // Inventory Module & Modal
    inventory_title: 'Operasional Gudang & Inventaris',
    stock_operations: 'Operasi Stok',
    inventory_subtitle: 'Audit mutasi stok, pantau kapasitas gudang, dan valuasi material.',
    inventory_management: 'Manajemen Inventaris',
    stock_movements: 'Audit Mutasi Stok',
    stock_movements_subtitle: 'Riwayat lengkap pergerakan stok masuk (IN) dan stok keluar (OUT).',
    total_warehouse_value: 'Total Valuasi Gudang',
    storage_capacity: 'Kapasitas Ruang Gudang',
    last_audit: 'Audit Terakhir',
    zone_utilization: 'Utilisasi Zona Penyimpanan',
    all_movements: 'Semua Mutasi',
    incoming_in: 'Barang Masuk (Produksi)',
    outgoing_out: 'Barang Keluar (Distribusi)',
    movement_id: 'Kode Mutasi',
    mutation_type: 'Tipe Mutasi',
    mutation_date: 'Tanggal & Waktu',
    export_report: 'Ekspor Laporan',
    stock_out_btn: 'Keluarkan Stok (Keluar)',
    record_stock_out_title: 'Catat Pengeluaran Stok Gudang',
    record_stock_out_desc: 'Kurangi stok gudang untuk distribusi pesanan atau pemeliharaan',
    quantity_deducted: 'Jumlah Pengurangan Stok',
    confirm_stock_out: 'Konfirmasi Pengeluaran Stok',

    // Reports Module
    reports_title: 'Laporan & Analitik Operasional',
    intelligence_center: 'Pusat Inteligensi',
    reports_subtitle: 'Metrik yield mendalam, performa mesin, dan proyeksi ketersediaan stok.',
    reports_analytics: 'Laporan & Analitik',
    monthly_yield: 'Tren Hasil Produksi Bulanan',
    top_products_distribution: 'Distribusi Volume Produk Utama',
    machine_performance_heatmap: 'Heatmap Utilisasi Mesin',
    inventory_forecast: 'Proyeksi Stok 30 Hari ke Depan',

    // Users Module
    users_title: 'Manajemen Akses & Hak Pengguna',
    access_control: 'Kontrol Akses & Keamanan',
    users_subtitle: 'Kelola akun pengguna, tetapkan tingkatan peran, dan hak akses sistem.',
    user_management: 'Manajemen Pengguna',
    registered_users: 'Daftar Pengguna Terdaftar',
    invite_user: 'Buat Akun Pengguna',
    role_permissions: 'Matriks Perizinan Peran',
    all_roles: 'Semua Peran',
    admin_role: 'Administrator',
    manager_role: 'Manajer',
    supervisor_role: 'Supervisor',
    operator_role: 'Operator',
    admin_role_desc: 'Akses penuh seluruh sistem. Mengelola konfigurasi, tagihan, audit, dan pengguna.',
    supervisor_role_desc: 'Mengawasi jalur produksi, menghasilkan laporan analitik, dan mengatur jadwal.',
    operator_role_desc: 'Menjalankan instruksi kerja, mencatat batch mesin, dan melihat data lini.',
    manage_roles: 'Kelola akses platform, tingkatan peran, dan izin keamanan.',

    // Settings Module (All 6 Tabs)
    system_settings: 'Pengaturan & Preferensi Sistem',
    system_config: 'Konfigurasi Sistem',
    settings_description: 'Kelola konfigurasi akun, lokalisasi bahasa, dan preferensi antarmuka.',
    search_settings: 'Cari pengaturan...',
    select_language: 'Pilih Bahasa Antarmuka',
    language: 'Bahasa',
    language_subtitle: 'Pilih bahasa antarmuka untuk pusat kendali.',
    appearance: 'Tampilan Visual',
    appearance_subtitle: 'Sesuaikan tema, kontras, dan kepadatan antarmuka pengguna.',
    theme: 'Mode Tema',
    theme_dark: 'Mode Gelap (Dark)',
    theme_light: 'Mode Terang (Light)',
    high_contrast: 'Mode Kontras Tinggi',
    high_contrast_desc: 'Tingkatkan keterbacaan untuk lingkungan pencahayaan ekstrem.',
    ui_density: 'Kepadatan Antarmuka',
    density_comfortable: 'Nyaman (Standar)',
    density_compact: 'Padat (Industri Berkepadatan Tinggi)',
    accent_color: 'Palet Warna Aksen',
    accent_blue: 'Biru Industri (Forge)',
    accent_emerald: 'Hijau Otomasi (Emerald)',
    accent_amber: 'Kuning Siber (Amber)',
    accent_violet: 'Ungu Teknologi (Violet)',
    preview_format: 'Pratinjau Format & Angka',

    profile: 'Profil Pengguna',
    profile_info: 'Profil & Identitas Pengguna',
    profile_subtitle: 'Kelola data pribadi operator, divisi kerja, dan kontak darurat.',
    full_name: 'Nama Lengkap',
    job_title: 'Jabatan Pekerjaan',
    department: 'Departemen / Divisi',
    phone_number: 'Nomor Telepon',
    timezone: 'Zona Waktu Sistem',
    save_profile: 'Simpan Profil',
    profile_updated: 'Informasi profil berhasil diperbarui.',

    security: 'Keamanan & Sandi',
    security_title: 'Keamanan & Autentikasi',
    security_subtitle: 'Kelola sandi keamanan, autentikasi multi-faktor, dan sesi aktif.',
    current_password: 'Sandi / Kunci Saat Ini',
    new_password: 'Kunci Keamanan Baru',
    confirm_password: 'Konfirmasi Kunci Baru',
    update_password: 'Ganti Kata Sandi',
    two_factor_auth: 'Autentikasi Dua Faktor (2FA)',
    two_factor_desc: 'Wajibkan kode token autentikator saat masuk.',
    active_sessions: 'Sesi Login Workstation Aktif',
    revoke_other_sessions: 'Putuskan Sesi Lain',
    session_revoked: 'Semua sesi jarak jauh lainnya telah diputus.',
    password_updated: 'Kunci keamanan berhasil diperbarui.',

    notifications: 'Notifikasi Sistem',
    notification_rules: 'Aturan Notifikasi & Kanal Peringatan',
    notification_rules_desc: 'Atur pemicu peringatan otomatis untuk telemetri pabrik.',
    channel_in_app: 'Peringatan Dalam Aplikasi',
    channel_email: 'Ringkasan Email',
    channel_audio: 'Sirine Audio Peringatan',
    alert_low_stock: 'Peringatan Batas Aman Stok Rendah',
    alert_maintenance: 'Peringatan Pemeliharaan Berkala Mesin',
    alert_shift_batch: 'Laporan Output Produksi Batch Shift',
    alert_db_sync: 'Peringatan Sinkronisasi Basis Data & Telemetri',
    save_notifications: 'Simpan Aturan Notifikasi',
    notifications_saved: 'Aturan notifikasi berhasil disimpan.',

    system: 'Konfigurasi Sistem',
    system_infra: 'Infrastruktur Inti & Mesin Server',
    system_infra_desc: 'Endpoint runtime backend aktif, topologi basis data, dan polling telemetri.',
    backend_api_url: 'Endpoint Backend Go',
    mssql_db_host: 'Kluster Basis Data MSSQL 2022',
    auto_sync_interval: 'Interval Polling Sinkronisasi Otomatis',
    default_export_format: 'Format Standar Ekspor Data',
    telemetry_log_level: 'Tingkat Pencatatan Log Telemetri',
    trigger_backup: 'Jalankan Pencadangan Database Manual',
    backup_initiated: 'Snapshot database berhasil dimulai pada Port 6063.',
    system_config_saved: 'Konfigurasi infrastruktur berhasil diperbarui.',

    configuration: 'Konfigurasi',
    config_active: 'Opsi konfigurasi untuk',
    config_active_suffix: 'sedang aktif.',
    system_roles: 'Peran Sistem',
    manage_user_access: 'Kelola hak akses dan perizinan akun.',
    add_user: 'Tambah Pengguna',
    save_preferences: 'Simpan Preferensi',

    // Help Center Module & FAQs
    help_center_title: 'Pusat Bantuan & Panduan Sistem',
    help_center_subtitle: 'Panduan sistem, prosedur operasional standar, dan dokumentasi teknis pabrik.',
    back_to_dashboard: 'Kembali ke Dashboard Eksekutif',
    faq_title: 'Pertanyaan yang Sering Diajukan (FAQ)',
    documentation: 'Dokumentasi',
    contact_support: 'Dukungan Teknis',
    support_team_hours: 'Tim rekayasa siap siaga (Pemantauan 24/7)',
    open_support_ticket: 'Buka Tiket Bantuan',
    quick_start_guide: 'Arsitektur Sistem & Port',
    quick_start_guide_desc: 'Ringkasan Go Backend (Port 6060), Next.js Frontend (Port 6061), dan MSSQL 2022 (Port 6063).',
    production_flow_guide: 'Alur Pencatatan Produksi',
    production_flow_guide_desc: 'Bagaimana log produksi secara otomatis memicu mutasi stok MASUK dengan transaksi ACID.',
    inventory_rules_guide: 'Batas Aman Inventaris',
    inventory_rules_guide_desc: 'Peringatan visual: Hijau (Normal), Kuning (Stok Rendah), dan Merah (Stok Habis).',
    faq_1_q: 'Bagaimana cara mencatat produk jadi hasil manufaktur?',
    faq_1_a: 'Gunakan tombol Aksi Cepat "+ Catat Produksi" di dashboard atau buka menu Log Produksi.',
    faq_2_q: 'Bagaimana cara kerja penambahan stok otomatis?',
    faq_2_a: 'Setiap kali log produksi disimpan, backend Go mengeksekusi transaksi basis data yang mencatat mutasi stok MASUK dan memperbarui stok saat ini.',
    faq_3_q: 'Apakah saya bisa mengganti bahasa dan tema kapan saja?',
    faq_3_a: 'Ya, gunakan pemilih Bahasa di bilah navigasi atas atau buka menu Pengaturan Sistem.',

    // Notifications Modal
    notification_center: 'Pusat Notifikasi',
    notifications_desc: 'Peringatan operasional real-time, peringatan stok, dan log sistem pabrik.',
    mark_all_read: 'Tandai semua dibaca',
    clear_all: 'Hapus semua',
    new_badge: 'baru',
    all_filter: 'Semua',
    unread_filter: 'Belum Dibaca',
    critical_filter: 'Kritis',
    no_notifications: 'Tidak ada notifikasi baru',
    produce_stock_btn: 'Produksi Stok',
    schedule_btn: 'Jadwalkan',
    notif_1_title: 'Peringatan Stok Rendah Tercapai',
    notif_1_msg: 'Servo Motor A-12 saat ini bersisa 2 unit (Ambang minimum: 10 unit). Disarankan segera dilakukan pengisian stok.',
    notif_2_title: 'Peringatan Pemeliharaan Berkala',
    notif_2_msg: 'Mesin CNC-01 (Milling) telah mencapai 500 jam operasi. Pemeriksaan dijadwalkan dalam 4 jam.',
    notif_3_title: 'Batch Produksi Shift Selesai',
    notif_3_msg: 'Shift A menyelesaikan 45 unit Titanium Casing Alpha oleh operator J. Miller. Mutasi stok +45 pcs.',
    notif_4_title: 'Sinkronisasi Basis Data MSSQL Berhasil',
    notif_4_msg: 'Cadangan otomatis dan sinkronisasi indeks telemetri selesai di port 6063.',

    // Logout Modal
    confirm_sign_out: 'Konfirmasi Keluar Akun',
    sign_out_desc: 'Apakah Anda yakin ingin mengakhiri sesi? Anda harus masuk kembali untuk mengakses pusat kendali.',
    active_session: 'Sesi Aktif',
    yes_sign_out: 'Ya, Keluar Akun',
    signing_out: 'Sedang Mengeluarkan...',

    // Relative Time & Status
    '2_mins_ago': '2 menit lalu',
    '5_mins_ago': '5 menit lalu',
    '25_mins_ago': '25 menit lalu',
    '1_hour_ago': '1 jam lalu',
    '3_hours_ago': '3 jam lalu',
    yesterday: 'Kemarin',
    offline_status_label: 'Offline',

    // Table Headers & Labels
    time: 'Waktu',
    operator: 'Operator',
    machine_id: 'ID Mesin',
    quantity: 'Jumlah',
    status: 'Status',
    last_activity: 'Aktivitas Terakhir',
    actions: 'Tindakan',
    role: 'Peran',
    user: 'Pengguna',
    last_login: 'Terakhir Masuk',
    active_status_label: 'Aktif',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operator',

    // Units & Measures
    units: 'unit',
    pcs: 'pcs',
    produce: 'Produksi',
    view_all: 'Lihat Semua',
    showing: 'Menampilkan',
    of: 'dari',
    loading: 'Memuat...',

    // Timeframes & Days
    tf_7d: '7H',
    tf_30d: '30H',
    tf_ytd: 'YTD',
    days_mon: 'Sen',
    days_tue: 'Sel',
    days_wed: 'Rab',
    days_thu: 'Kam',
    days_fri: 'Jum',
    days_sat: 'Sab',
    days_sun: 'Min',

    // Buttons
    save: 'Simpan Produk',
    cancel: 'Batal',
    submit: 'Kirim',
    view: 'Lihat',
    edit: 'Ubah',
    delete: 'Hapus',
    interface_language: 'Bahasa Antarmuka',
  },

  ar: {
    // Navigation & Sidebar
    dashboard: 'لوحة التحكم التنفيذية',
    products: 'كتالوج المنتجات',
    production_logs: 'سجلات الإنتاج',
    inventory: 'المخزون والمستودع',
    reports: 'التقارير والتحليلات',
    users: 'إدارة المستخدمين',
    settings: 'إعدادات النظام',
    help: 'مركز المساعدة',
    logout: 'تسجيل الخروج',
    main_menu: 'القائمة الرئيسية',
    enterprise_automation: 'أتمتة العمليات الصناعية',

    // Dashboard Page
    executive_dashboard: 'لوحة التحكم التنفيذية',
    smart_control: 'الأتمتة الذكية',
    realtime_overview: 'نظرة عامة فورية وشاملة على عمليات التصنيع ومراقبة المخزون.',
    refresh: 'تحديث البيانات المباشرة',
    sync_data: 'مزامنة البيانات',

    // Header & Quick Actions
    search_placeholder: 'ابحث في العمليات، المنتجات، السجلات...',
    export: 'تصدير البيانات',
    new_action: 'إجراء سريع',
    add_new_product: '+ إضافة منتج جديد',
    record_production: 'تسجيل الإنتاج اليومي',
    record_stock_out: 'تسجيل صرف المخزون',

    // KPI Summary Cards
    total_products: 'إجمالي المنتجات النشطة',
    today_production: 'إنتاج اليوم',
    current_inventory: 'مستوى المخزون الحالي',
    low_stock_alerts: 'تنبيهات المخزون المنخفض',
    production_efficiency: 'كفاءة خط الإنتاج (OEE)',
    active_catalog: 'منتج نشط في الكتالوج',
    vs_daily_target: 'مقارنة بالهدف اليومي',
    total_items_in_stock: 'إجمالي القطع في المستودع',
    require_attention: 'منتجات تتطلب الانتباه',
    optimal_output: 'إنتاجية الخط المثلى',

    // Dashboard widgets
    quick_actions: 'العمليات السريعة',
    quick_actions_subtitle: 'إدخال بيانات التصنيع المباشرة ومعاملات المستودع',
    system_status: 'حالة البنية التحتية',
    system_status_subtitle: 'مراقبة فورية لصحة قاعدة البيانات وواجهة الخادم البرمجية',
    all_systems_nominal: 'جميع الأنظمة تعمل بشكل طبيعي',
    last_sync_text: 'آخر مزامنة: منذ دقيقتين (المنفذ ٦٠٦٠ / ٦٠٦٣)',
    online: 'متصل',
    synced: 'متزامن',
    action_required: 'مطلوب اتخاذ إجراء',
    low_stock_subtitle: 'المنتجات التي انخفضت عن حد الأمان الأدنى',
    live_output: 'الإنتاج المباشر',
    production_analytics: 'تحليلات الإنتاج',
    production_analytics_subtitle: 'المعدل اليومي لمخرجات التصنيع ومؤشر الكفاءة في الوقت الفعلي',

    // Products Module & Modal
    products_management: 'كتالوج المنتجات والمواصفات',
    master_catalog: 'الكتالوج الرئيسي',
    products_subtitle: 'إدارة مواصفات التصنيع، قوائم المواد، وحدود الأمان للمخزون.',
    search_products: 'ابحث عن منتج بالاسم أو الرمز...',
    add_product: 'إضافة منتج',
    add_product_title: 'إضافة منتج جديد',
    add_product_desc: 'أدخل تفاصيل المنتج لتتبع المخزون في المصنع بدقة.',
    product_name: 'اسم المنتج',
    category: 'الفئة',
    unit_of_measure: 'وحدة القياس',
    initial_stock: 'المخزون الأولي',
    initial_stock_label: 'المخزون الأولي',
    min_stock_level: 'الحد الأدنى للمخزون',
    min_stock_label: 'الحد الأدنى للمخزون',
    primary_supplier: 'المورد الرئيسي',
    primary_supplier_label: 'المورد الرئيسي',
    description: 'الوصف',
    active_status: 'الحالة التشغيلية',
    all_categories: 'جميع الفئات',
    all_statuses: 'جميع الحالات',
    in_stock_status: 'متوفر بالمخزون',
    low_stock_status: 'مخزون منخفض',
    out_of_stock_status: 'نفد المخزون',
    product_id: 'رمز المنتج',
    unit: 'الوحدة',
    current_stock: 'المخزون الحالي',
    min_stock: 'الحد الأدنى',
    save_product: 'حفظ المنتج',
    category_electronics: 'الإلكترونيات والأتمتة',
    category_mechanical: 'القطع الميكانيكية',
    category_sensors: 'المستشعرات والمحولات',
    category_plcs: 'وحدات التحكم المنطقية PLC',
    category_raw: 'المواد الخام',
    unit_pcs: 'قطع (قطعة)',
    unit_box: 'صناديق (صندوق)',
    unit_meter: 'أمتار (متر)',
    unit_kg: 'كيلوغرام (كغ)',

    // Production Logs Module & Modal
    production_logs_title: 'سجلات إنتاج المصنع',
    live_manufacturing_data: 'بيانات الإنتاج المباشرة',
    production_logs_subtitle: 'تسجيل الإنتاج لكل وردية، متابعة الآلات، ومراقبة الكميات المصنعة.',
    new_log_entry: 'إدخال سجل إنتاج جديد',
    recent_logs: 'سجل الإنتاج الأخير',
    record_daily_production: 'تسجيل الإنتاج اليومي',
    record_daily_desc: 'تسجيل كمية الإنتاج وتحديث المخزون الوارد تلقائياً',
    select_product: 'المنتج المستهدف',
    select_product_prompt: 'اختر المنتج المستهدف *',
    select_machine: 'الآلة المخصصة',
    assigned_machine: 'الآلة / محطة العمل',
    quantity_produced: 'الكمية المنتجة',
    output_quantity: 'كمية الإنتاج',
    shift: 'وردية العمل',
    operator_name: 'المشغل المسؤول',
    operator_name_label: 'اسم المشغل',
    submit_log: 'حفظ سجل الإنتاج',
    save_production_log: 'حفظ سجل الإنتاج',
    log_id: 'رمز السجل',
    timestamp: 'وقت التسجيل',
    filter_by_machine: 'جميع الآلات',

    // Inventory Module & Modal
    inventory_title: 'إدارة المستودع والمخزون',
    stock_operations: 'عمليات المخزون',
    inventory_subtitle: 'تدقيق حركات المخزون، مراقبة سعة التخزين، وتقييم المواد في الوقت الفعلي.',
    inventory_management: 'إدارة المخزون',
    stock_movements: 'سجل تدقيق حركة المخزون',
    stock_movements_subtitle: 'سجل شامل لجميع حركات المخزون الواردة (IN) والصادرة (OUT).',
    total_warehouse_value: 'إجمالي قيمة المستودع',
    storage_capacity: 'السعة التخزينية للمستودع',
    last_audit: 'آخر تدقيق للمخزون',
    zone_utilization: 'نسبة استغلال مناطق التخزين',
    all_movements: 'جميع الحركات',
    incoming_in: 'وارد (إنتاج)',
    outgoing_out: 'صادر (توزيع)',
    movement_id: 'رمز الحركة',
    mutation_type: 'نوع الحركة',
    mutation_date: 'التاريخ والوقت',
    export_report: 'تصدير التقرير',
    stock_out_btn: 'صرف مخزون (صادر)',
    record_stock_out_title: 'تسجيل صرف المخزون',
    record_stock_out_desc: 'خصم المخزون لطلبات التوزيع أو الصيانة الدورية',
    quantity_deducted: 'الكمية المصروفة',
    confirm_stock_out: 'تأكيد صرف المخزون',

    // Reports Module
    reports_title: 'التقارير والتحليلات التشغيلية',
    intelligence_center: 'مركز التحليلات الذكية',
    reports_subtitle: 'مؤشرات الإنتاجية التفصيلية، أداء الآلات، وتوقعات استهلاك المخزون.',
    reports_analytics: 'التقارير والتحليلات',
    monthly_yield: 'مؤشر الإنتاج الشهري',
    top_products_distribution: 'توزيع حجم المنتجات الأكثر إنتاجاً',
    machine_performance_heatmap: 'خريطة أداء وتشغيل الآلات',
    inventory_forecast: 'توقعات المخزون لـ ٣٠ يوماً قادمة',

    // Users Module
    users_title: 'إدارة المستخدمين وصلاحيات الوصول',
    access_control: 'التحكم بالوصول والأمان',
    users_subtitle: 'إدارة حسابات المستخدمين، تعيين مستويات الأدوار، وتكوين الأذونات الأمنية.',
    user_management: 'إدارة المستخدمين',
    registered_users: 'المستخدمون المسجلون في النظام',
    invite_user: 'إنشاء حساب مستخدم',
    role_permissions: 'مصفوفة أذونات الأدوار',
    all_roles: 'جميع الأدوار',
    admin_role: 'مسؤول',
    manager_role: 'مدير',
    supervisor_role: 'مشرف',
    operator_role: 'مشغل',
    admin_role_desc: 'صلاحيات كاملة للنظام. إدارة الإعدادات، الفواتير، التدقيق، والمستخدمين.',
    supervisor_role_desc: 'الإشراف على خطوط الإنتاج، إصدار التقارير، وإدارة الجداول.',
    operator_role_desc: 'تنفيذ أوامر العمل، تسجيل دفعات الآلات، وعرض البيانات.',
    manage_roles: 'إدارة صلاحيات الوصول، الأدوار، والأذونات الأمنية.',

    // Settings Module (All 6 Tabs)
    system_settings: 'إعدادات النظام والتفضيلات',
    system_config: 'تكوين النظام',
    settings_description: 'إدارة إعدادات الحساب، اللغة، وتفضيلات واجهة التحكم.',
    search_settings: 'البحث في الإعدادات...',
    select_language: 'اختيار لغة الواجهة',
    language: 'لغة الواجهة',
    language_subtitle: 'اختر لغتك المفضلة لمركز التحكم.',
    appearance: 'المظهر والتصميم',
    appearance_subtitle: 'تخصيص نمط المظهر وتباين الشاشة وكثافة العرض.',
    theme: 'وضع السمة',
    theme_dark: 'الوضع الداكن (Dark)',
    theme_light: 'الوضع الفاتح (Light)',
    high_contrast: 'وضع التباين العالي',
    high_contrast_desc: 'زيادة تباين الشاشة لسهولة القراءة في البيئات الصناعية.',
    ui_density: 'كثافة الواجهة',
    density_comfortable: 'مريح (قياسي)',
    density_compact: 'مضغوط (صناعي عالي الكثافة)',
    accent_color: 'لوحة الألوان الرئيسية',
    accent_blue: 'أزرق صناعي (Forge)',
    accent_emerald: 'أخضر أتمتة (Emerald)',
    accent_amber: 'كهرماني سيبراني (Amber)',
    accent_violet: 'بنفسجي تكنولوجي (Violet)',
    preview_format: 'معاينة الأرقام والتواريخ',

    profile: 'الملف الشخصي',
    profile_info: 'بيانات الملف الشخصي',
    profile_subtitle: 'إدارة بيانات المشغل والبريد الإلكتروني والمهام الوظيفية.',
    full_name: 'الاسم الكامل',
    job_title: 'المسمى الوظيفي',
    department: 'القسم / الإدارة',
    phone_number: 'رقم الهاتف',
    timezone: 'المنطقة الزمنية للنظام',
    save_profile: 'حفظ الملف الشخصي',
    profile_updated: 'تم تحديث بيانات الملف الشخصي بنجاح.',

    security: 'الأمان وكلمة المرور',
    security_title: 'الأمان والمصادقة',
    security_subtitle: 'إدارة كلمات المرور والمصادقة الثنائية وجلسات العمل النشطة.',
    current_password: 'كلمة المرور الحالية',
    new_password: 'مفتاح الأمان الجديد',
    confirm_password: 'تأكيد المفتاح الجديد',
    update_password: 'تحديث كلمة المرور',
    two_factor_auth: 'المصادقة الثنائية (2FA)',
    two_factor_desc: 'فرض رمز المصادقة أو تطبيق Authenticator عند الدخول.',
    active_sessions: 'جلسات العمل النشطة',
    revoke_other_sessions: 'إنهاء الجلسات الأخرى',
    session_revoked: 'تم إنهاء جميع الجلسات البعيدة الأخرى.',
    password_updated: 'تم تحديث كلمة المرور بنجاح.',

    notifications: 'إشعارات النظام',
    notification_rules: 'قواعد الإشعارات وقنوات التنبيه',
    notification_rules_desc: 'تكوين محفزات التنبيه التلقائي للمصنع.',
    channel_in_app: 'تنبيهات داخل التطبيق',
    channel_email: 'ملخص البريد الإلكتروني',
    channel_audio: 'إنذار صوتي مسموع',
    alert_low_stock: 'تنبيه حد الأمان للمخزون المنخفض',
    alert_maintenance: 'تنبيه الصيانة الوقائية للآلات',
    alert_shift_batch: 'تقارير دفعات الإنتاج للورديات',
    alert_db_sync: 'تحذيرات مزامنة قاعدة البيانات والقياس عن بعد',
    save_notifications: 'حفظ قواعد الإشعارات',
    notifications_saved: 'تم حفظ إعدادات الإشعارات بنجاح.',

    system: 'تكوين النظام',
    system_infra: 'البنية التحتية والمحرك الأساسي',
    system_infra_desc: 'نقاط نهاية الخادم المباشرة، وهيكلية قاعدة البيانات، ومعدل المزامنة.',
    backend_api_url: 'نقطة نهاية خادم Go',
    mssql_db_host: 'مجموعة قاعدة بيانات MSSQL 2022',
    auto_sync_interval: 'الفاصل الزمني للمزامنة التلقائية',
    default_export_format: 'الصيغة الافتراضية لتصدير البيانات',
    telemetry_log_level: 'مستوى تسجيل القياس عن بُعد',
    trigger_backup: 'تشغيل النسخ الاحتياطي اليدوي لقاعدة البيانات',
    backup_initiated: 'تم بدء التقاط نسخة احتياطية لقاعدة البيانات على المنفذ ٦٠٦٣.',
    system_config_saved: 'تم تحديث تكوين البنية التحتية بنجاح.',

    configuration: 'التكوين',
    config_active: 'خيارات التكوين لـ',
    config_active_suffix: 'نشطة حالياً.',
    system_roles: 'أدوار النظام',
    manage_user_access: 'إدارة وصول المستخدمين والأذونات.',
    add_user: 'إضافة مستخدم',
    save_preferences: 'حفظ التفضيلات',

    // Help Center Module & FAQs
    help_center_title: 'مركز المساعدة وقاعدة المعرفة',
    help_center_subtitle: 'أدلة النظام، إجراءات التشغيل القياسية، والوثائق الفنية للمصنع.',
    back_to_dashboard: 'العودة إلى لوحة التحكم التنفيذية',
    faq_title: 'الأسئلة الشائعة (FAQ)',
    documentation: 'الوثائق الفنية',
    contact_support: 'الدعم الفني',
    support_team_hours: 'فريق الدعم الهندسي على أهبة الاستعداد (مراقبة ٢٤/٧)',
    open_support_ticket: 'فتح تذكرة دعم',
    quick_start_guide: 'هيكلية النظام والمنافذ',
    quick_start_guide_desc: 'نظرة عامة على خادم Go (المنفذ ٦٠٦٠)، واجهة Next.js (المنفذ ٦٠٦١)، وقاعدة MSSQL (المنفذ ٦٠٦٣).',
    production_flow_guide: 'سير عمل تسجيل الإنتاج',
    production_flow_guide_desc: 'كيف تُنشئ سجلات الإنتاج حركات مخزون واردة تلقائياً مع معاملات ACID المضمونة.',
    inventory_rules_guide: 'حدود أمان المخزون',
    inventory_rules_guide_desc: 'تحذيرات مرئية ملونة: الأخضر (طبيعي)، الكهرماني (مخزون منخفض)، والأحمر (نفد المخزون).',
    faq_1_q: 'كيف يمكنني تسجيل المنتجات المصنعة الجاهزة؟',
    faq_1_a: 'استخدم زر الإجراء السريع "+ تسجيل الإنتاج" في لوحة التحكم أو انتقل إلى صفحة سجلات الإنتاج.',
    faq_2_q: 'كيف تعمل إعادة تعبئة المخزون تلقائياً؟',
    faq_2_a: 'عند حفظ سجل إنتاج، يُنفذ الخادم معاملة برمجية تنشئ حركة مخزون واردة وتحدث رصيد المخزون فوراً.',
    faq_3_q: 'هل يمكنني تغيير اللغة والمظهر في أي وقت؟',
    faq_3_a: 'نعم، استخدم قائمة اختيار اللغة في الشريط العلوي أو انتقل إلى صفحة إعدادات النظام.',

    // Notifications Modal
    notification_center: 'مركز الإشعارات',
    notifications_desc: 'تنبيهات تشغيلية في الوقت الفعلي وتحذيرات المخزون وسجلات النظام.',
    mark_all_read: 'تحديد الكل كمقروء',
    clear_all: 'مسح الكل',
    new_badge: 'جديد',
    all_filter: 'الكل',
    unread_filter: 'غير مقروء',
    critical_filter: 'حرج',
    no_notifications: 'لا توجد إشعارات حالياً',
    produce_stock_btn: 'إنتاج المخزون',
    schedule_btn: 'جدولة',
    notif_1_title: 'تم تجاوز حد المخزون المنخفض',
    notif_1_msg: 'محرك السيرفو A-12 يحتوي حالياً على قطعتين فقط (الحد الأدنى: ١٠ قطع). يوصى بإعادة التوريد فوراً.',
    notif_2_title: 'تحذير موعد الصيانة المجدولة',
    notif_2_msg: 'وصلت الآلة CNC-01 إلى ٥٠٠ ساعة تشغيل. الفحص الدوري مستحق خلال ٤ ساعات.',
    notif_3_title: 'اكتمال دفعة الإنتاج للوردية',
    notif_3_msg: 'أكملت الوردية الأولى ٤٥ قطعة من الهيكل التيتانيوم Alpha بواسطة المشغل ج. ميلر. تم تحديث المخزون +٤٥ قطعة.',
    notif_4_title: 'نجاح مزامنة قاعدة بيانات MSSQL',
    notif_4_msg: 'اكتمل النسخ الاحتياطي التلقائي ومزامنة المؤشرات بنجاح على المنفذ ٦٠٦٣.',

    // Logout Modal
    confirm_sign_out: 'تأكيد تسجيل الخروج',
    sign_out_desc: 'هل أنت متأكد من رغبتك في إنهاء الجلسة؟ ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى مركز التحكم.',
    active_session: 'جلسة نشطة',
    yes_sign_out: 'نعم، تسجيل الخروج',
    signing_out: 'جاري تسجيل الخروج...',

    // Relative Time & Status
    '2_mins_ago': 'منذ دقيقتين',
    '5_mins_ago': 'منذ ٥ دقائق',
    '25_mins_ago': 'منذ ٢٥ دقيقة',
    '1_hour_ago': 'منذ ساعة',
    '3_hours_ago': 'منذ ٣ ساعات',
    yesterday: 'أمس',
    offline_status_label: 'غير متصل',

    // Table Headers & Labels
    time: 'الوقت',
    operator: 'المشغل',
    machine_id: 'رمز الآلة',
    quantity: 'الكمية',
    status: 'الحالة',
    last_activity: 'آخر نشاط',
    actions: 'الإجراءات',
    role: 'الدور',
    user: 'المستخدم',
    last_login: 'آخر دخول',
    active_status_label: 'نشط',
    admin: 'مسؤول',
    supervisor: 'مشرف',
    operator_text: 'مشغل',

    // Units & Measures
    units: 'وحدة',
    pcs: 'قطعة',
    produce: 'إنتاج',
    view_all: 'عرض الكل',
    showing: 'عرض',
    of: 'من',
    loading: 'جاري التحميل...',

    // Timeframes & Days
    tf_7d: '٧ أيام',
    tf_30d: '٣٠ يوماً',
    tf_ytd: 'منذ بداية العام',
    days_mon: 'الإثنين',
    days_tue: 'الثلاثاء',
    days_wed: 'الأربعاء',
    days_thu: 'الخميس',
    days_fri: 'الجمعة',
    days_sat: 'السبت',
    days_sun: 'الأحد',

    // Buttons
    save: 'حفظ المنتج',
    cancel: 'إلغاء',
    submit: 'إرسال',
    view: 'عرض',
    edit: 'تعديل',
    delete: 'حذف',
    interface_language: 'لغة الواجهة',
  },

  es: {
    // Navigation & Sidebar
    dashboard: 'Panel de Control',
    products: 'Catálogo de Productos',
    production_logs: 'Registros de Producción',
    inventory: 'Gestión de Inventario',
    reports: 'Informes y Análisis',
    users: 'Gestión de Usuarios',
    settings: 'Configuración del Sistema',
    help: 'Centro de Ayuda',
    logout: 'Cerrar Sesión',
    main_menu: 'Menú Principal',
    enterprise_automation: 'Automatización Empresarial',

    // Dashboard Page
    executive_dashboard: 'Panel Ejecutivo',
    smart_control: 'Automatización Inteligente',
    realtime_overview: 'Resumen en tiempo real de operaciones de fabricación e inventario global.',
    refresh: 'Sincronizar Datos',
    sync_data: 'Sincronizar',

    // Header & Quick Actions
    search_placeholder: 'Buscar operaciones, productos, registros...',
    export: 'Exportar Datos',
    new_action: 'Acción Rápida',
    add_new_product: '+ Añadir Producto',
    record_production: 'Registrar Producción',
    record_stock_out: 'Registrar Salida de Stock',

    // KPI Summary Cards
    total_products: 'Total de Productos Activos',
    today_production: 'Producción de Hoy',
    current_inventory: 'Nivel de Stock Actual',
    low_stock_alerts: 'Alertas de Stock Bajo',
    production_efficiency: 'Eficiencia de Línea (OEE)',
    active_catalog: 'Artículos activos en catálogo',
    vs_daily_target: 'vs objetivo diario',
    total_items_in_stock: 'Total de artículos en stock',
    require_attention: 'Artículos requieren atención',
    optimal_output: 'Rendimiento óptimo de línea',

    // Dashboard widgets
    quick_actions: 'Operaciones Rápidas',
    quick_actions_subtitle: 'Entradas directas de fabricación y transacciones de inventario',
    system_status: 'Estado de la Infraestructura',
    system_status_subtitle: 'Monitoreo en vivo de la base de datos y la API backend',
    all_systems_nominal: 'Todos los Sistemas Nominales',
    last_sync_text: 'Última sinc.: hace 2 min (Puerto 6060/6063)',
    online: 'En Línea',
    synced: 'Sincronizado',
    action_required: 'Acción Requerida',
    low_stock_subtitle: 'Productos por debajo del umbral mínimo de seguridad',
    live_output: 'Producción en Vivo',
    production_analytics: 'Análisis de Producción',
    production_analytics_subtitle: 'Tendencia diaria de producción y eficiencia en tiempo real',

    // Products Module & Modal
    products_management: 'Catálogo de Productos y Especificaciones',
    master_catalog: 'Catálogo Maestro',
    products_subtitle: 'Gestionar especificaciones de fabricación, lista de materiales y umbrales de seguridad.',
    search_products: 'Buscar productos por nombre o ID...',
    add_product: 'Añadir Producto',
    add_product_title: 'Añadir Nuevo Producto',
    add_product_desc: 'Ingrese los detalles del producto para el seguimiento de inventario.',
    product_name: 'Nombre del Producto',
    category: 'Categoría',
    unit_of_measure: 'Unidad de Medida',
    initial_stock: 'Stock Inicial',
    initial_stock_label: 'Stock Inicial',
    min_stock_level: 'Nivel Mínimo de Stock',
    min_stock_label: 'Nivel Mínimo de Stock',
    primary_supplier: 'Proveedor Principal',
    primary_supplier_label: 'Proveedor Principal',
    description: 'Descripción',
    active_status: 'Estado Activo',
    all_categories: 'Todas las Categorías',
    all_statuses: 'Todos los Estados',
    in_stock_status: 'En Stock',
    low_stock_status: 'Stock Bajo',
    out_of_stock_status: 'Agotado',
    product_id: 'ID de Producto',
    unit: 'Unidad',
    current_stock: 'Stock Actual',
    min_stock: 'Stock Mínimo',
    save_product: 'Guardar Producto',
    category_electronics: 'Electrónica y Automatización',
    category_mechanical: 'Piezas Mecánicas',
    category_sensors: 'Sensores y Transductores',
    category_plcs: 'PLCs y Controladores',
    category_raw: 'Materias Primas',
    unit_pcs: 'Piezas (pzas)',
    unit_box: 'Cajas (caja)',
    unit_meter: 'Metros (m)',
    unit_kg: 'Kilogramos (kg)',

    // Production Logs Module & Modal
    production_logs_title: 'Registros de Producción y Fabricación',
    live_manufacturing_data: 'Datos de Planta en Vivo',
    production_logs_subtitle: 'Registrar producción por turno, monitorear máquinas y lotes.',
    new_log_entry: 'Nueva Entrada de Producción',
    recent_logs: 'Historial de Producción Reciente',
    record_daily_production: 'Registrar Producción Diaria',
    record_daily_desc: 'Registrar cantidad producida y actualizar stock entrante automáticamente',
    select_product: 'Producto Destino',
    select_product_prompt: 'Seleccionar Producto Destino *',
    select_machine: 'Máquina Asignada',
    assigned_machine: 'Máquina / Puesto de Trabajo',
    quantity_produced: 'Cantidad Producida',
    output_quantity: 'Cantidad de Salida',
    shift: 'Turno de Trabajo',
    operator_name: 'Operador a Cargo',
    operator_name_label: 'Nombre del Operador',
    submit_log: 'Guardar Registro de Producción',
    save_production_log: 'Guardar Registro de Producción',
    log_id: 'ID de Registro',
    timestamp: 'Fecha y Hora',
    filter_by_machine: 'Todas las Máquinas',

    // Inventory Module & Modal
    inventory_title: 'Gestión de Inventario y Operaciones de Almacén',
    stock_operations: 'Operaciones de Stock',
    inventory_subtitle: 'Auditar movimientos, monitorear capacidad y valorar materiales en tiempo real.',
    inventory_management: 'Gestión de Inventario',
    stock_movements: 'Auditoría de Movimientos de Stock',
    stock_movements_subtitle: 'Historial completo de movimientos de entrada (IN) y salida (OUT) de almacén.',
    total_warehouse_value: 'Valor Total del Almacén',
    storage_capacity: 'Capacidad de Almacenamiento',
    last_audit: 'Última Auditoría de Stock',
    zone_utilization: 'Utilización de Zona',
    all_movements: 'Todos los Movimientos',
    incoming_in: 'Entrada (Producción)',
    outgoing_out: 'Salida (Despacho)',
    movement_id: 'ID de Movimiento',
    mutation_type: 'Tipo de Movimiento',
    mutation_date: 'Fecha y Hora',
    export_report: 'Exportar Informe',
    stock_out_btn: 'Despachar Stock (Salida)',
    record_stock_out_title: 'Registrar Salida de Stock',
    record_stock_out_desc: 'Deducir stock para distribución o mantenimiento',
    quantity_deducted: 'Cantidad a Deducir',
    confirm_stock_out: 'Confirmar Salida de Stock',

    // Reports Module
    reports_title: 'Informes y Análisis Operativos',
    intelligence_center: 'Centro de Inteligencia',
    reports_subtitle: 'Métricas de rendimiento, desglose de máquinas y pronósticos de inventario.',
    reports_analytics: 'Informes y Analítica',
    monthly_yield: 'Tendencia de Rendimiento Mensual',
    top_products_distribution: 'Distribución de Volumen de Productos',
    machine_performance_heatmap: 'Mapa de Calor de Rendimiento de Máquinas',
    inventory_forecast: 'Pronóstico de Stock a 30 Días',

    // Users Module
    users_title: 'Gestión de Usuarios y Control de Accesos',
    access_control: 'Control de Acceso y Seguridad',
    users_subtitle: 'Gestionar credenciales, asignar niveles de rol y configurar autorizaciones.',
    user_management: 'Gestión de Usuarios',
    registered_users: 'Usuarios Registrados en la Plataforma',
    invite_user: 'Crear Cuenta de Usuario',
    role_permissions: 'Matriz de Permisos por Rol',
    all_roles: 'Todos los Roles',
    admin_role: 'Administrador',
    manager_role: 'Gerente',
    supervisor_role: 'Supervisor',
    operator_role: 'Operador',
    admin_role_desc: 'Acceso total al sistema. Configuración global, auditorías y gestión de cuentas.',
    supervisor_role_desc: 'Supervisa líneas de producción, genera informes y gestiona horarios.',
    operator_role_desc: 'Ejecuta órdenes de trabajo, registra lotes y consulta métricas.',
    manage_roles: 'Gestionar accesos, roles y permisos de seguridad.',

    // Settings Module (All 6 Tabs)
    system_settings: 'Configuración del Sistema y Preferencias',
    system_config: 'Configuración del Sistema',
    settings_description: 'Administra la configuración de tu cuenta, idioma y preferencias del sistema.',
    search_settings: 'Buscar configuraciones...',
    select_language: 'Seleccionar Idioma de Interfaz',
    language: 'Idioma de Interfaz',
    language_subtitle: 'Elige tu idioma preferido para el centro de control.',
    appearance: 'Apariencia Visual',
    appearance_subtitle: 'Personaliza el tema visual, contraste y densidad del diseño.',
    theme: 'Modo de Tema',
    theme_dark: 'Modo Oscuro (Dark)',
    theme_light: 'Modo Claro (Light)',
    high_contrast: 'Modo de Alto Contraste',
    high_contrast_desc: 'Aumenta el contraste para mejor legibilidad en entornos industriales.',
    ui_density: 'Densidad de Interfaz',
    density_comfortable: 'Cómodo (Estándar)',
    density_compact: 'Compacto (Alta Densidad)',
    accent_color: 'Paleta de Color de Acento',
    accent_blue: 'Azul Industrial (Forge)',
    accent_emerald: 'Verde Automatización (Emerald)',
    accent_amber: 'Ámbar Ciber (Amber)',
    accent_violet: 'Violeta Tecnológico (Violet)',
    preview_format: 'Vista Previa de Formatos y Números',

    profile: 'Perfil de Usuario',
    profile_info: 'Perfil e Identidad de Usuario',
    profile_subtitle: 'Administra tus credenciales de operador, departamento y datos de contacto.',
    full_name: 'Nombre Completo',
    job_title: 'Título del Puesto',
    department: 'Departamento / División',
    phone_number: 'Teléfono de Contacto',
    timezone: 'Zona Horaria del Sistema',
    save_profile: 'Guardar Perfil',
    profile_updated: 'Información de perfil actualizada con éxito.',

    security: 'Seguridad y Contraseña',
    security_title: 'Seguridad y Autenticación',
    security_subtitle: 'Administra claves de acceso, autenticación de dos factores y sesiones activas.',
    current_password: 'Clave / Contraseña Actual',
    new_password: 'Nueva Clave de Seguridad',
    confirm_password: 'Confirmar Nueva Clave',
    update_password: 'Cambiar Contraseña',
    two_factor_auth: 'Autenticación de Dos Factores (2FA)',
    two_factor_desc: 'Requerir código de aplicación autenticadora al iniciar sesión.',
    active_sessions: 'Sesiones de Estación de Trabajo Activas',
    revoke_other_sessions: 'Cerrar Otras Sesiones',
    session_revoked: 'Todas las demás sesiones remotas han sido cerradas.',
    password_updated: 'Clave de seguridad actualizada correctamente.',

    notifications: 'Notificaciones del Sistema',
    notification_rules: 'Reglas de Notificación y Canales de Alerta',
    notification_rules_desc: 'Configura activadores de alerta para la telemetría automatizada de fábrica.',
    channel_in_app: 'Alertas en la Aplicación',
    channel_email: 'Resumen por Correo',
    channel_audio: 'Sirena / Timbre de Audio',
    alert_low_stock: 'Alerta de Umbral de Seguridad de Stock Bajo',
    alert_maintenance: 'Alerta de Mantenimiento Preventivo de Máquinas',
    alert_shift_batch: 'Informes de Producción de Lotes por Turno',
    alert_db_sync: 'Advertencias de Sincronización de Base de Datos y Telemetría',
    save_notifications: 'Guardar Reglas de Notificación',
    notifications_saved: 'Reglas de notificación guardadas con éxito.',

    system: 'Configuración del Sistema',
    system_infra: 'Infraestructura Central y Motor',
    system_infra_desc: 'Puntos finales del servidor en vivo, topología de base de datos y sondeo.',
    backend_api_url: 'Punto Final Backend Go',
    mssql_db_host: 'Clúster de Base de Datos MSSQL 2022',
    auto_sync_interval: 'Intervalo de Sondeo de Autosincronización',
    default_export_format: 'Formato Predeterminado de Exportación',
    telemetry_log_level: 'Nivel de Registro de Telemetría',
    trigger_backup: 'Iniciar Copia de Seguridad Manual de Base de Datos',
    backup_initiated: 'Instantánea de base de datos iniciada en el Puerto 6063.',
    system_config_saved: 'Configuración de infraestructura actualizada.',

    configuration: 'Configuración',
    config_active: 'Opciones de configuración para',
    config_active_suffix: 'están activas.',
    system_roles: 'Roles del Sistema',
    manage_user_access: 'Gestionar acceso y permisos de usuarios.',
    add_user: 'Añadir Usuario',
    save_preferences: 'Guardar Preferencias',

    // Help Center Module & FAQs
    help_center_title: 'Centro de Ayuda y Conocimiento',
    help_center_subtitle: 'Guías del sistema, procedimientos operativos y documentación técnica.',
    back_to_dashboard: 'Volver al Panel Ejecutivo',
    faq_title: 'Preguntas Frecuentes (FAQ)',
    documentation: 'Documentación',
    contact_support: 'Soporte Técnico',
    support_team_hours: 'Equipo de ingeniería disponible (Monitoreo 24/7)',
    open_support_ticket: 'Abrir Ticket de Soporte',
    quick_start_guide: 'Arquitectura y Puertos',
    quick_start_guide_desc: 'Resumen de Backend Go (Puerto 6060), Next.js Frontend (Puerto 6061) y MSSQL (Puerto 6063).',
    production_flow_guide: 'Flujo de Registro de Producción',
    production_flow_guide_desc: 'Cómo los registros de producción actualizan el stock entrante con transacciones ACID.',
    inventory_rules_guide: 'Límites de Seguridad de Stock',
    inventory_rules_guide_desc: 'Alertas visuales: Verde (Normal), Ámbar (Stock Bajo) y Carmesí (Agotado).',
    faq_1_q: '¿Cómo registro productos manufacturados terminados?',
    faq_1_a: 'Utilice el botón de Acción Rápida "+ Registrar Producción" en el panel de control o en Registros de Producción.',
    faq_2_q: '¿Cómo funciona la reposición automática de stock?',
    faq_2_a: 'Cada vez que se guarda un registro, el backend ejecuta una transacción que crea un movimiento de entrada y actualiza el stock.',
    faq_3_q: '¿Puedo cambiar el idioma y el tema en cualquier momento?',
    faq_3_a: 'Sí, use el selector de idioma global en la barra superior o en Configuración del Sistema.',

    // Notifications Modal
    notification_center: 'Centro de Notificaciones',
    notifications_desc: 'Alertas operativas en tiempo real, advertencias de stock y registros del sistema.',
    mark_all_read: 'Marcar todo como leído',
    clear_all: 'Borrar todo',
    new_badge: 'nuevo',
    all_filter: 'Todo',
    unread_filter: 'No leído',
    critical_filter: 'Crítico',
    no_notifications: 'No hay notificaciones',
    produce_stock_btn: 'Producir Stock',
    schedule_btn: 'Programar',
    notif_1_title: 'Alerta de Stock Bajo Activada',
    notif_1_msg: 'El servomotor A-12 tiene actualmente 2 unidades (Mínimo: 10 unidades). Se recomienda reabastecer.',
    notif_2_title: 'Aviso de Mantenimiento Programado',
    notif_2_msg: 'La máquina CNC-01 alcanzó 500 horas de funcionamiento. Revisión requerida en 4 horas.',
    notif_3_title: 'Lote de Producción de Turno Completado',
    notif_3_msg: 'El turno A completó 45 unidades de Carcasa de Titanio Alpha por el operador J. Miller. Stock +45 pzas.',
    notif_4_title: 'Sincronización de Base de Datos MSSQL Exitosa',
    notif_4_msg: 'Copia de seguridad automática y sincronización de índices completadas con éxito en el puerto 6063.',

    // Logout Modal
    confirm_sign_out: 'Confirmar Cierre de Sesión',
    sign_out_desc: '¿Está seguro de que desea finalizar su sesión? Necesitará iniciar sesión nuevamente para acceder al centro de control.',
    active_session: 'Sesión Activa',
    yes_sign_out: 'Sí, Cerrar Sesión',
    signing_out: 'Cerrando sesión...',

    // Relative Time & Status
    '2_mins_ago': 'Hace 2 min',
    '5_mins_ago': 'Hace 5 min',
    '25_mins_ago': 'Hace 25 min',
    '1_hour_ago': 'Hace 1 hora',
    '3_hours_ago': 'Hace 3 horas',
    yesterday: 'Ayer',
    offline_status_label: 'Desconectado',

    // Table Headers & Labels
    time: 'Hora',
    operator: 'Operador',
    machine_id: 'ID de Máquina',
    quantity: 'Cantidad',
    status: 'Estado',
    last_activity: 'Última Actividad',
    actions: 'Acciones',
    role: 'Rol',
    user: 'Usuario',
    last_login: 'Último Acceso',
    active_status_label: 'Activo',
    admin: 'Admin',
    supervisor: 'Supervisor',
    operator_text: 'Operador',

    // Units & Measures
    units: 'unidades',
    pcs: 'pzas',
    produce: 'Producir',
    view_all: 'Ver Todo',
    showing: 'Mostrando',
    of: 'de',
    loading: 'Cargando...',

    // Timeframes & Days
    tf_7d: '7D',
    tf_30d: '30D',
    tf_ytd: 'YTD',
    days_mon: 'Lun',
    days_tue: 'Mar',
    days_wed: 'Mié',
    days_thu: 'Jue',
    days_fri: 'Vie',
    days_sat: 'Sáb',
    days_sun: 'Dom',

    // Buttons
    save: 'Guardar Producto',
    cancel: 'Cancelar',
    submit: 'Enviar',
    view: 'Ver',
    edit: 'Editar',
    delete: 'Eliminar',
    interface_language: 'Idioma de Interfaz',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const emptySubscribe = () => () => {}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const mounted = useSyncExternalStore(
    emptySubscribe,
    () => true,
    () => false
  )

  const [language, setLanguageState] = useState<Language>('en')

  // Initialize from storage once mounted
  const storedLang = useSyncExternalStore(
    emptySubscribe,
    () => {
      const saved = localStorage.getItem('forge_lang') as Language
      return saved && ['en', 'id', 'ar', 'es'].includes(saved) ? saved : null
    },
    () => null
  )

  const currentLanguage = storedLang || language

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('forge_lang', lang)
    }
  }

  const isRTL = currentLanguage === 'ar'

  const t = (key: string): string => {
    return translations[currentLanguage]?.[key] || translations['en']?.[key] || key
  }

  const formatNumber = (value: number | string | null | undefined): string => {
    return formatNumberByLang(value, currentLanguage)
  }

  const formatDate = (date?: Date | string | number, options?: Intl.DateTimeFormatOptions): string => {
    return formatDateByLang(date, currentLanguage, options)
  }

  return (
    <LanguageContext.Provider value={{ language: currentLanguage, setLanguage, t, formatNumber, formatDate, isRTL }}>
      <div
        dir="ltr"
        className={currentLanguage === 'ar' ? 'font-arabic' : ''}
        style={{ minHeight: '100%' }}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
